### ISSUE TITLE
MySQL_Packet::wait_for_client() - wrong packet size 

### ISSUE THREAD

**Issue by ceotto** [ChuckBell/MySQL_Connector_Arduino#1]
The MySQL_Packet.h is using a
`#define MYSQL_MIN_BYTES     8`
which is wrong and **MySQL_Packet::wait_for_client()** allways exits per tiime-out.

It seems to function a little better changing the following define to 5 bytes:
`#define MYSQL_MIN_BYTES     5`

In fact from the docs (https://dev.mysql.com/doc/internals/en/packet-OK_Packet.html) we can observe that the ok packet is 1+2+2 bytes (at least):

```
Table 14.1 Payload of OK Packet
Type            Name            Description
int<1>          header          [00] or [fe] the OK packet header
int<lenenc>     affected_rows   affected rows
int<lenenc>     last_insert_id  last insert-id

```

**Comment by ChuckBell** [comment]
You may want to check that. 8 is the correct value. Remember, the lengths are encoded.

**Comment by ChuckBell** [comment]
Observe:

Example OK Packet
Hexadecimal ASCII
----------- -----
field_count 00 .
affected_rows 01 .
insert_id 00 .
server_status 02 00 ..
warning_count 00 00 ..

**Comment by ceotto** [comment]
good evening dr Bell.
I'm using a raspbian server 5.5: "Connected to server version 5.5.44-0+deb8u1".
And I'm quite sure that the answer is 5 byte long, as per this code:
void MySQL_Packet::read_packet() {
  byte local[4];

  if (buffer != NULL)
    free(buffer);

  int avail_bytes = wait_for_client();
  while (avail_bytes < 4) {
    avail_bytes = wait_for_client();
  }

After you can wait for the rest ...


  avail_bytes = wait_for_client();
  while (avail_bytes < packet_len) {
    avail_bytes = wait_for_client();
  }

best regards
Franco Ceotto
OCP DBA, Performance Engineer
franco_ceotto@yahoo.it

 

    Il Mercoledì 22 Giugno 2016 23:12, Dr. Charles Bell <notifications@github.com> ha scritto:
 

 Observe:

Example OK Packet
Hexadecimal ASCII
----------- -----
field_count 00 .
affected_rows 01 .
insert_id 00 .
server_status 02 00 ..
warning_count 00 00 ..

**Comment by ChuckBell** [comment]
You may want to capture the packets and analyze them because I am consistently seeing 8+ bytes in Ok packets.

**Comment by ceotto** [comment]
Hi.
YOU are waiting for 5 bytes ... in read-packet, but in the sub wait-for-client a compile-time const of 8 is cabled in the code.
Best regards.Frank



Inviato da Yahoo Mail su Android 
 
  Il gio, 23 giu, 2016 alle 21:07, Dr. Charles Bell<notifications@github.com> ha scritto:   You may want to capture the packets and analyze them because I am consistently seeing 8+ bytes in Ok packets.

**Comment by ChuckBell** [comment]
Ok, let me know how you get it worked out. :)
