### ISSUE TITLE
MKRGSM Connection

### ISSUE THREAD

**Issue by DiegoD4i** [ChuckBell/MySQL_Connector_Arduino#100]
Hello, excuse me. I've been researching bookshops for days. I find it wonderful but I can not make it work with a MKR GSM 1400. This board uses MKRGSM.h instead of WIFI101.h
If I use "GSMClient client;" does not detect any error but does not connect to the Database
Can you guide me ?. The MKRGSM.h library is not compatible?
Thank you

**Comment by ChuckBell** [comment]
Hi,

It appears from the website: https://www.arduino.cc/en/Reference/MKRGSM ...

> The library tries to be as compatible as possible with the current Ethernet and WiFi101library. Porting a program from an Arduino Ethernet or WiFi101 library to an Arduino with the MKR GSM 1400 should be fairly easy. While it is not possible to simply run Ethernet or WiFi101 compatible code on the MKR GSM 1400 as-is, some minor, library specific, modifications will be necessary, like including the GSM and GPRS specific libraries and getting network configuration settings from your cellular network provider.


So, it would require modifying the connector code in order to fully support this library. In short, no, it is not compatible.

Dr. Bell

**Comment by ChuckBell** [comment]
Closed due to inactivity. Please open a new ticket if this is still relevant.
