### ISSUE TITLE
Seems to be stuck at "Connecting to SQL..."

### ISSUE THREAD

**Issue by Zane1996** [ChuckBell/MySQL_Connector_Arduino#105]
Hi,
I am using an ESP32 so I had to modify the MySQL_Packet_h file to allow use of the MySQL connector, however the serial monitor gets stuck on "Connecting to SQL..". Have any idea as to what would cause this? I'll post the code below. 

[code]

#include <WiFi.h>
#include <MySQL_Connection.h>
#include <MySQL_Cursor.h>

IPAddress server_addr(127,0,0,1);  // IP of the MySQL *server* here
char user[] = "root";              // MySQL user login username
char password[] = "";        // MySQL user login password

// Sample query
char INSERT_SQL[] = "INSERT INTO data (sensor,location,value1,value2,value3) VALUES ('Thermocouple', 'office', 20, 20, 20)";

// WiFi card example
char ssid[] = "";         // your SSID
char pass[] = "";     // your SSID Password
             
             
WiFiClient client;             // Use this for WiFi instead of EthernetClient            
MySQL_Connection conn(&client);
MySQL_Cursor* cursor;

void setup()
{
  Serial.begin(115200);
  while (!Serial); // wait for serial port to connect. Needed for Leonardo only

  // Begin WiFi section
  Serial.printf("\nConnecting to %s", ssid);
  WiFi.begin(ssid, pass);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  // print out info about the connection:
  Serial.println("\nConnected to network");
  Serial.print("My IP address is: ");
  Serial.println(WiFi.localIP());

  Serial.print("Connecting to SQL...  ");
  if (conn.connect(server_addr, 3306, user, password))
    Serial.println("OK.");
  else
    Serial.println("FAILED.");
  
  // create MySQL cursor object
  cursor = new MySQL_Cursor(&conn);
}

void loop()
{
  if (conn.connected())
    cursor->execute(INSERT_SQL);

  delay(5000);
}
[/code]

**Comment by ChuckBell** [comment]
Hi,

Yep. The IP address of the server is incorrect. You need the external IP
address of the server where MySQL is running. 127.0.0.1 is the loopback
address. Won’t work. :)

Dr. Bell

**Comment by Zane1996** [comment]
Where would I find the external IP address? Sorry I'm very new to this.

**Comment by ChuckBell** [comment]
Depends on the OS. If Linux or macOS, run ifconfig. If Windows, run
ipconfig /all. Look for the interface you’re using - typically WiFi.

**Comment by Zane1996** [comment]
I added the IP address and it is still stuck at "Connecting to SQL...".  Could it be something else?

**Comment by ChuckBell** [comment]
Yes. Check the manual. It can be permissions, password, firewall, network, etc. There are suggestions on how to diagnose in the manual.

**Comment by michaelradhuber** [comment]
I had the same problem on my Wemos D1 mini PRO, and after some debugging I ended up commenting out MYSQL_Packet.cpp, lines 292-296. like this:

`  /*int avail_bytes = wait_for_client();
  while (avail_bytes < 4) {
    avail_bytes = wait_for_client();
    Serial.print("Waiting for 4 avail bytes.Currently we have: "); Serial.println("avail_bytes");
  }
  */`

I would suggest to implement these changes for all ESP8266 chips. I always got stuck in this loop, it didn't stall, just stuck there for ever... Now it appears to be working fine.

Thanks for your work @ChuckBell
