### ISSUE TITLE
How to port this MySQL connector to ESP32?

### ISSUE THREAD

**Issue by pcbtborges** [ChuckBell/MySQL_Connector_Arduino#107]
Hi, Will this library work with ESP32?
Thanks

**Comment by ChuckBell** [comment]
Yea but only if you use an Arduino compatible WiFi library and modify the
mysql_packet.h file accordingly. See other posts on the topic.

**Comment by pcbtborges** [comment]
OK, thanks for the response.
What do you mean using "Arduino compatible WiFi library"
I just use the standard WiFi.h (and WiFisecure.h) library that is loaded when you install ESP32 on the Arduino IDE, Will this one work?
What sort of change will be required on mysql_packet.h?
Thanks

**Comment by ChuckBell** [comment]
A compatible library is one that implements the same interface as the
Arduino classes (same methods). See #include Ethernet.h.

**Comment by pcbtborges** [comment]
Ok, I see.
But instead of making reference to Ethernet.h can I compare Arduino Wifi.h and ESP32 WiFi.h?
Thanks

**Comment by ChuckBell** [comment]
Correct. Substitute whatever WiFi library you want to use for 
Ethernet.h. Try to compile. If the connector compiles, you've got a good 
WiFi library. If not, try to find another.
