### ISSUE TITLE
Help with select

### ISSUE THREAD

**Issue by sidneysamir** [ChuckBell/MySQL_Connector_Arduino#110]
Hi Dr. ChuckBell!

I am trying to check if a value exists on a table with the format below.

Item |     Code  |  Date
--------------------------
1      |     Samir | Date1
2      |    Chaves| Date2

The query that I am using is:
char query[] = "SELECT Item FROM bdardui.Tab1  WHERE Code= 'Chaves'";

I am trying to get the value from the column item with this code:

void VerificarValor(){

row_values *row = NULL;
int head_count = 0;

MySQL_Cursor *cur_mem = new MySQL_Cursor(&conn);
// Execute the query
cur_mem->execute(query);
// Fetch the columns (required) but we don't use them.
column_names *columns = cur_mem->get_columns();
// Read the row (we are only expecting the one)
do {
 row = cur_mem->get_next_row();
 if (row != NULL) {
 head_count = atol(row->values[0]);
 }
} while (row != NULL);
// Deleting the cursor also frees up memory used
cur_mem->close();
delete cur_mem;

Serial.print(" Resultado = ");
Serial.println(head_count);  
}

But the result I am having is "Resultado= 0" (What I need is the value of the column Item when the column Code has "Chaves".  Can you help me?

**Comment by ChuckBell** [comment]
Ok, here's a possible fix.

int MySQL_Packet::wait_for_bytes(int bytes_need)
{
const long wait_till = millis() + MYSQL_DATA_TIMEOUT;
int num = 0;
long now = 0;

do
{
now = millis();
num += client->available();

Change that last line in the code above (MySQL_Packet.cpp) - add + before the =. Let me know if it works.

**Comment by ChuckBell** [comment]
I ran your code unchanged and it worked for me with this change on 5.6 and
without it on 8.0. I’m thinking permissions still.

**Comment by sidneysamir** [comment]
Doctor Charles, your support was wonderful!

The problem was solved!!! Thank you very much for your attention.
