### ISSUE TITLE
ESP32-POE-ISO

### ISSUE THREAD

**Issue by TeKiLLa1985** [ChuckBell/MySQL_Connector_Arduino#114]
Hi,
is it possible to get the MySQL Connector running on a ESP32-POE-ISO, i have compile it but i can t connect to the MariaDB.

**Comment by ChuckBell** [comment]
The connector is not supported for use with non-Oracle distributions of
MySQL. However, many have had success running on the ESP platform. Just be
sure to use an Arduino Ethernet compatible network library. See the other
notes on this site for hints.

**Comment by TeKiLLa1985** [comment]
So, we have made it now i can write things to my Database but one problem i can't solve i have a 4 byte input from my RFID and i bring that down to a 4 byte hex string and now i wan t to send it to my database but i have no idea how

**Comment by TeKiLLa1985** [comment]
`#include <MySQL_Connection.h>
#include <MySQL_Cursor.h>
#include <MySQL_Encrypt_Sha1.h>
#include <MySQL_Packet.h>
#include <SPI.h>
#include <MFRC522.h>
#include <ETH.h>

const int RST_PIN = 5; // Reset pin
const int SS_PIN = 13; // Slave select pin

static bool eth_connected = false;

MFRC522 mfrc522(SS_PIN, RST_PIN); // Create MFRC522 instance

IPAddress server_addr(192, 168, 251, 130); // IP of the MySQL *server* here
char user[] = "TEST01";              // MySQL user login username
char password[] = "XXX";        // MySQL user login password

char INSERT_SQL[] = "INSERT INTO test.hello_arduino (message) VALUES ()";

void setup() {
  Serial.begin(9600);
  ETH.begin();
  Serial.println("Connecting...");
  while (!Serial); // Do nothing if no serial port is opened (added for Arduinos based on ATMEGA32U4)
  SPI.begin(); // Init SPI bus
  mfrc522.PCD_Init(); // Init MFRC522
  mfrc522.PCD_DumpVersionToSerial(); // Show details of PCD - MFRC522 Card Reader details
  Serial.println(F("Scan PICC to see UID, SAK, type, and data blocks..."));
}


void loop() // Hier beginnt der Loop-Teil
{
  if ( ! mfrc522.PICC_IsNewCardPresent()) // Wenn keine Karte in Reichweite ist...
  {
    return; // ...springt das Programm zurück vor die if-Schleife, womit sich die Abfrage wiederholt.
  }
  if ( ! mfrc522.PICC_ReadCardSerial()) // Wenn kein RFID-Sender ausgewählt wurde
  {
    return; // ...springt das Programm zurück vor die if-Schleife, womit sich die Abfrage wiederholt.
  }
  Serial.print("Die ID des RFID-TAGS lautet:"); // "Die ID des RFID-TAGS lautet:" wird auf den Serial Monitor geschrieben.
  for (byte i = 0; i < mfrc522.uid.size; i++)
  {
    Serial.print(mfrc522.uid.uidByte[i], HEX); // Dann wird die UID ausgelesen, die aus vier einzelnen Blöcken besteht und der Reihe nach an den Serial Monitor gesendet. Die Endung Hex bedeutet, dass die vier Blöcke der UID als HEX-Zahl ausgegeben wird
    //Serial.print(" "); // Der Befehl „Serial.print(" ");“ sorgt dafür, dass zwischen den einzelnen ausgelesenen Blöcken ein Leerzeichen steht.
    
  }
  Serial.println(); // Mit dieser Zeile wird auf dem Serial Monitor nur ein Zeilenumbruch gemacht.
  Serial.print("\nConnecting to ");



  WiFiClient client;
  MySQL_Connection conn((Client *)&client);
  if (conn.connect(server_addr, 3306, user, password)) {
    Serial.println("Database connected.");
  }
  else
    Serial.println("Connection failed.");
  Serial.println("Recording data.");

  // Initiate the query class instance
  MySQL_Cursor *cur_mem = new MySQL_Cursor(&conn);
  // Execute the query
  cur_mem->execute(INSERT_SQL);
  // Note: since there are no results, we do not need to read any data
  // Deleting the cursor also frees up memory used
  delete cur_mem;
  Serial.println("closing connection\n");
  //client.stop();

}`

**Comment by ChuckBell** [comment]
Closed due to inactivity.
