### ISSUE TITLE
Cannot find class defintion for Client

### ISSUE THREAD

**Issue by baqwas** [ChuckBell/MySQL_Connector_Arduino#115]
Hello,

Can someone please point me to the correct library for **Client** as used in the following example:

`MySQL_Connection db_conn((**Client** *)&WiFi_client);`

The MySQL_Connector_Arduino works fine for me with MKR1000 and Nano33 boards but the MXChip AZ3166 board has a different set of libraries for Wi-Fi:

- [AZ3166WiFi](https://github.com/microsoft/devkit-sdk/tree/master/AZ3166/src/libraries/WiFi/src)

- [AZ3166WiFiClient](https://github.com/microsoft/devkit-sdk/blob/master/AZ3166/src/libraries/WiFi/src/AZ3166WiFiClient.h)

How can I inherit Client with the AZ3166WiFi libraries? Thanks.

Kind regards.

**Comment by baqwas** [comment]
I understand your comments; did my nominal search prior to posting. All the method (and public field) names are identical. But I couldn't locate any reference to **Client** anywhere except in the Arduino docs, and casting to **EthernetClient** (which inherits **Client** presumably) does not work.

**Comment by baqwas** [comment]
BTW, the solution was to update the conditional pre-processing directive to include the Wi-Fi library for the board.

**Comment by ChuckBell** [comment]
Yep. That was the suggestion.
