### ISSUE TITLE
cannot connect to SQL DB due to dynamic ip

### ISSUE THREAD

**Issue by kmf909** [ChuckBell/MySQL_Connector_Arduino#12]
based on the connect_wifi sketch it needed ip address of SQL dB. in my case the SQL dB  not having static IP and it advise (link below) to use domain name. could advise on how to edit the sketch to fit the requirement.

https://blogs.msdn.microsoft.com/psssql/2014/03/27/dont-rely-on-a-static-ip-address-for-your-sql-database/

**Comment by ChuckBell** [comment]
It’s in the manual:

Can I use a hostname instead of an IP address for the server?

Yes, but it requires using the dns library as follows.

#include <Dns.h>
…
char hostname[] = "www.google.com <http://www.google.com/>”;  // change to your server’s hostname/URL
…
IPAddress server_ip;
DNSClient dns;
dns.begin(Ethernet.dnsServerIP());
dns.getHostByName(hostname, server_ip);  
Serial.println(server_ip)
Serial.println("Connecting...");
if (conn.connect(server_ip, 3306, user, password)) {
…

**Comment by ChuckBell** [comment]
You could also use the MySQL Router.

**Comment by kmf909** [comment]
Hi Dr chuck. Thank you for the prompt reply. I'll will updates the result.

**Comment by kmf909** [comment]
Hi Dr, i try to use connect_by_hostname sketch instead and change ethernet to wifi (ESP8266) and i got error as below. i thought it may caused by EPS8266 , then i try to compile the original sketch but it also produce same error. could you assist on this.

 multiple
 definition of `hostname'
sketch/connect_by_hostname.ino.cpp.o:(.data.hostname+0x0): first defined here

**Comment by ChuckBell** [comment]
I will need to see your whole sketch, but this normally means you've redeclared a variable. In this case, possibly including the connector code twice or simply redeclaring it. But again, send me your sketch to my email address and I'll check it. Example code works fine for me.

**Comment by kmf909** [comment]
Hi Dr

attached is the sketch (connect_by_hostname) that i edited to use
wifi(esp8266) instead of ethernet.

Regards,
Rehman laili

On Fri, Feb 10, 2017 at 10:24 PM, Dr. Charles Bell <notifications@github.com

**Comment by ChuckBell** [comment]
No sketch was attached. You will need to send it to my email directly:

d r c h a r l e s b e l l at g m a i l dot c o m

**Comment by kgdx** [comment]
Do you get any answer about this issue? I have the same, when trying to connect to by host name instead of IP i get the same error, I'm using a ESP8266 (wemos d1 mini). If you can share an example of using host name and the Esp8266wifi library could be great. 
Thanks in advanced.

**Comment by ChuckBell** [comment]
No, sorry. I have not found an ESP8266 library that implements the DNS class (or something like it). If you find one, please share!

**Comment by ChuckBell** [comment]
Wait! Try this one: https://github.com/esp8266/Arduino

Follow the directions to install it. Then use the following code to add to your sketch (placed appropriately).

char host[] = "www.google.com"; // change to your server's hostname/URL
…
DNSClient dns_client;   // DNS instance
IPAddress server_ip;
…
  // Begin DNS lookup
  dns_client.begin(Ethernet.dnsServerIP());
  dns_client.getHostByName(host, server_ip);
  Serial.println(server_ip);
  // End DNS lookup

Dr. Bell

**Comment by kmf909** [comment]
Hi Dr

i try to edit "connect by hostname" according to your suggestion, the good news is i can upload to HUZZAH board ( no error as previous) and the not so good news is the serial show connection failed. btw i use azure SQL dB. i verify the dB connection with SQL server management studio. so now still searching the root cause.

**Comment by ChuckBell** [comment]
The connector is written for use with MySQL, it will not work with MS SQL Server.

**Comment by ChuckBell** [comment]
However, it appears you are using MySQL. Let's use that term, eh? ;)

There are all manner of reasons why you cannot connect. Please see the troubleshooting guide in the manual for things to try.

The best tool is the mysql client from your PC. Use it to try to connect to your Azure MySQL instance. If you can do that, then you can eliminate much of the normal user/account/grants issue. If you cannot, work on those three areas until you can successfully connect. Other than that, check for firewall issues, router/networking issues, etc. 

Also, use a simple WiFi example sketch to ensure you can connect to the Internet.

Again, all of this is in the manual.

**Comment by kmf909** [comment]
Hi Doc

my mistake .azure use their own SQL so not valid with this sketch. i also try amazon mysql but it doesn't support arduino due to security issue

**Comment by gombeluc** [comment]
Hello, I'm trying since one week ... to resolve internet address to ip address ... but without success. I tried your exemple : WiFi.hostByName("www.google.com",server_ip);
Serial.println(server_ip);   But no ip ....;
I tried also with dns ... idem
My shiel is an esp8266.
Have you any suggestion ?   Thank you in advance. Best regards  (Luc from Belgium :)
