### ISSUE TITLE
Could you help me making it compatible with SIM7000?

### ISSUE THREAD

**Issue by JJGR93** [ChuckBell/MySQL_Connector_Arduino#120]
Hello, thank you so much for this library. Could you help me making it compatible with GSM/GPRS/LTE SIM modules please?

**Comment by ChuckBell** [comment]
Well, that’s tricky. You will have to find a library that works over TCP and replace all Ethernet class calls in the connector library. However, be prepared for a lot of work as most GSM-ish libraries I’ve found do not support TCP. Most seem to be satisfied with HTTP.

**Comment by ChuckBell** [comment]
Closed due to inactivity.
