### ISSUE TITLE
MySQL Arduino interaction

### ISSUE THREAD

**Issue by ivaring** [ChuckBell/MySQL_Connector_Arduino#121]
Hello everybody.

I have to prepare a sketch to allow to registered and enabled users to get access to Arduino through the Connector. 
Is it possible to use the Connector first to select the right User from a table (using a card and sending the ID from Arduino to the database), asking to other table for authorization and finally allowing access or not. 
I'm starting by modifying basic select sketch, I'll post it here after finished first draft, thank you.

**Comment by ivaring** [comment]
First rough draft of sketch (with errors):

#include <Ethernet.h>
#include <MySQL_Connection.h>
#include <MySQL_Cursor.h>

#define PULSANTEPIN 6
#define LEDPIN 7

// inidirizzo MAC Ethernet Shield Arduino
byte mac_addr[] = { 0xA8, 0x61, 0x0A, 0xAE, 0x19, 0x34 }; 

// Arduino IP
IPAddress ip(10, 10, 10, 104);

IPAddress server_addr(10,10,10,252);  // IP del server MySQL (è il mio PC, non l'Arduino)

char user[] = "phpmyadmin";          // MySQL username login utente
char password[] = "phpmyadmin";      // MySQL password login utente

// Query Select USER
char SELECT_USER[] = "SELECT USER_ID FROM Morbegno.CITTADINO WHERE BADGE = %s"; // %s -> stringa
char query[128];

// Query Insert Record Conferimento
char INSERT_CONFERIMENTO[] = "INSERT INTO Morbegno.CARTA (USER_ID) VALUES %d";
char query2[128];

EthernetClient client;
MySQL_Connection conn((Client *)&client);

//----------------------------------------------------

void setup() {
  
  pinMode(PULSANTEPIN, INPUT);
  pinMode(LEDPIN, OUTPUT);
 
  delay(500);
  Serial.begin(115200);

  Ethernet.begin(mac_addr, ip);
 
  if (conn.connect(server_addr, 3306, user, password)) {
    Serial.println(F("Connected"));
  }
  else {
    Serial.println(F("Connection failed."));
  }
 
  Serial.println();
}

//----------------------------------------------------

void loop() {
  
  // turn off LED
  digitalWrite(LEDPIN, LOW);

 if (PULSANTEPIN == HIGH) {

  // turn on LED  
  digitalWrite(LEDPIN, HIGH);
 
  // Initiate the query class instance
  MySQL_Cursor *cur_mem = new MySQL_Cursor(&conn);

  // create the SELECT_USER query - taking 1 (USER_ID)
  sprintf(query, SELECT_USER, 1); // Create query and SELECT_USER and assign BADGE as criteria  1 in this case
 
  // Execute the SELECT_USER query
  cur_mem->execute(query);
  delete cur_mem;
  Serial.println("");

  // Read button state
  int pulsanteValue = digitalRead(PULSANTEPIN);

   // create the Conferimento query
  sprintf(query2, INSERT_CONFERIMENTO, 1);
   
  // Execute the INSERT_CONFERIMENTO query
  cur_mem->execute(query2);
  delete cur_mem;
  Serial.println("Data del conferimento registrata");
  
  Serial.println();
  }

  delay(1000);
}

**Comment by ivaring** [comment]
Another draft 

#include <Ethernet.h>
#include <MySQL_Connection.h>
#include <MySQL_Cursor.h>

//Configuracion de libreria Ethernet / MySQL

byte mac_addr[] = { 0xDE, 0xAD, 0xBE, 0xEF, 0xFE, 0xED };

IPAddress server_addr(10,10,10,104);  // servidor MySQL Raspberry
char user[] = "root";                 // MySQL username
char password[] = "12345";            // MySQL password
#define PORT_MYSQL 3306

//iniciamos librerias:
EthernetClient client;
MySQL_Connection conn((Client *)&client);

//para el pulsador
bool on_pulse = false;
#define PULSANTEPIN 6
#define LEDPIN 7

void setup(){
    pinMode(PULSANTEPIN, INPUT);
    pinMode(LEDPIN, OUTPUT);
    while (!Serial); //esperamos que se inicie el puerto serie
    Serial.begin(115200);
    Ethernet.begin(mac_addr); //por DHCP, no me importa ponerle ip fija por ahora
}

void loop(){
    if(digitalRead(PULSANTEPIN) == HIGH && on_pulse == false){
        on_pulse = false; //para emular un flipflop T
        digitalWrite(LEDPIN, HIGH);
        get_auth("3ds456dgf");// llama la función con el parámetro TESSERA para buscar la el usuario
        entry_record(999); // llama la función con el parámetro USER_ID 999 para grabar la entrada
    }
    if(digitalRead(PULSANTEPIN) == LOW && on_pulse == true){
        on_pulse = false;
        digitalWrite(LEDPIN, LOW);
    }
}

bool get_auth(char TESSERA){
    //buscamos el ID en la DB buscando si esta autorizado o no:
      if (conn.connect(server_addr, PORT_MYSQL, user, password)) {
        char SQL[] = "SELECT USER_ID FROM Morbegno.CITTADINO WHERE BADGE == TESSERA AND CARTA == 1";
        // ejecuta la query buscando el usuario
        char query[128];
        sscanf(query, SQL, TESSERA);
        MySQL_Cursor *cur_mem = new MySQL_Cursor(&conn);
        cur_mem->execute(query);
        delete cur_mem;
        conn.close();  
        Serial.println("Usuario encontrado y habilitado");
        return true;
  }
    Serial.println("No se encuentra el usuario o no habilitado");
    
    return false;
}

bool entry_record(int USER_ID){
  // guarda el dato del acceso en la tabla de la base de datos correspondiente
    if (conn.connect(server_addr, PORT_MYSQL, user, password)) {
        char SQL[] = "INSERT INTO Morbegno.CARTA (TIME,USER_ID) VALUES (NOW(),%d)";
        // ejecuta la query grabando los VALUES now y USER_ID que proviene del llamado a la funcion
        char query[128];
        sprintf(query, SQL, USER_ID);
        MySQL_Cursor *cur_mem = new MySQL_Cursor(&conn);
        cur_mem->execute(query);
        delete cur_mem;
        conn.close();  
        Serial.println("Ingreso grabado");
        return true;
  }
    Serial.println("No se puede grabar el ingreso");
  return false;
}

**Comment by ChuckBell** [comment]
Closed due to inactivity.
