### ISSUE TITLE
MySQL_Connector on Arduino Warning in compiler

### ISSUE THREAD

**Issue by formeforgit** [ChuckBell/MySQL_Connector_Arduino#123]
Hi,
im not speak english - please have indulgence

my first Arduniotest with query_result.ino give 5 error when once compile.
in next compile no error - while latest compiled file used

i have errormessage in 2 atached file (png and txt) - in codetags not passed note....

Enviroment:
ubuntu 18.04 - latest update/upgrade
Arduino 1.8.10
mysqlconnector 1.1.1

thanks for respond

![MySQL_error](https://user-images.githubusercontent.com/60822000/74089316-d4dd2000-4a97-11ea-8ace-8c5c856ec836.png)

[con_err.txt](https://github.com/ChuckBell/MySQL_Connector_Arduino/files/4174695/con_err.txt)

**Comment by ChuckBell** [comment]
I don't see errors, I see warnings. Can you post the complete error message? To fix the "no return" message, just edit the file shown and add the return statement. Some compilers complain; others don't.

**Comment by formeforgit** [comment]
Thanks for comment and remedy.

You have right - is not an a error. i have change the subject.
i have in MySQL_Encrypt_sha1.cpp two lines insert:
1) at line 89 in `size_t Encrypt_SHA1::write(uint8_t data)` 
2) at line 95 in `size_t Encrypt_SHA1::write(uint8_t* data, int length)`
new lines: `return(0);`

have you idea for rectification [-Wunused-parameter] in MySQL_Packet.cpp? 
thanks

**Comment by ChuckBell** [comment]
I compiled the code and do not see those errors. Those parameters are being used. So, let's try this. What board are you using and which programmer do you have selected? BTW, most warnings like this can be safely ignored.

**Comment by ChuckBell** [comment]
You can also just turn the warnings off in the preferences. Just saying...
