### ISSUE TITLE
Program crashes using both Mysql and Mqtt

### ISSUE THREAD

**Issue by yanguuu** [ChuckBell/MySQL_Connector_Arduino#127]
When I debug the Mysql upload program according to the routine, I transplanted it to the code with the Mqtt service, and found that the program crashed after a while. The program is stuck at "cur_mem-> execute (buff);", Then I annotate the mqtt service initialization statement in setup and the program runs normally.Does anyone encounter the same situation?

**Comment by ChuckBell** [comment]
Closed due to inactivity.
