### ISSUE TITLE
Connect to local MySQL

### ISSUE THREAD

**Issue by rodrigotabsan** [ChuckBell/MySQL_Connector_Arduino#129]
Hi,

I am trying to connect to 127.0.0.1 where I have a MySQL Server created with Wamp (phpMyAdmin).
The connect example can't connect to my database... what am i doing wrong?

Here is the code that I am using:

``#include <Ethernet.h>
#include <MySQL_Connection.h>

byte mac_addr[] = { 0x30, 0x5B, 0x3A, 0x7A, 0x0C, 0x0G };

IPAddress server_addr(127,0,0,1);  // IP of the MySQL *server* here
char user[] = "root";              // MySQL user login username
char password[] = "";        // MySQL user login password

EthernetClient client;
MySQL_Connection conn((Client *)&client);

void setup() {
  Serial.begin(9600);
  while (!Serial); // wait for serial port to connect
  Ethernet.begin(mac_addr);
  Serial.println("Connecting...");
  if (conn.connect(server_addr, 3306, user, password)) {
    delay(1000);
    // You would add your code here to run a query once on startup.
  }
  else
    Serial.println("Connection failed.");
  conn.close();
}

void loop() {
}``

Port is ok, password is ok and user is ok... what am i doing wrong?

I am using MySQL 8

Thanks in advance

**Comment by ChuckBell** [comment]
You cannot use the loopback address. You must use the IP address of the
computer hosting MySQL.
