### ISSUE TITLE
HANGS on "     MySQL_Cursor *cur_mem = new MySQL_Cursor(&conn);"

### ISSUE THREAD

**Issue by TomInIowa** [ChuckBell/MySQL_Connector_Arduino#130]
Thank you for sharing the sketch/library!!!!

Running on Arduino Uno with Ethernet Shield.
Running the sketch "querry_results"
Sometimes it works 5 or 10 times in a row.  Then it quits doing 
     MySQL_Cursor *cur_mem = new MySQL_Cursor(&conn);
I put Serial.println ... above and below the line

The serial monitor shows a  backward  question mark when it doesn't work.
from your function:  Ram:991
It starts working again (I haven't figured out why)

**Comment by ChuckBell** [comment]
Sounds like you’re running out of memory or the connection is dropping or hanging. Please ensure you’re doing the following:

- connect/disconnect in the loop() (not in setup())
- use free_row_boffer after each row is read
- use free_column_buffer after all columns are read
- delete the cursor 

You can also print the available memory on each pass through loop(), which should give you an idea if you are leaking memory.

If you’re still stumped, you can send me your sketch and I’ll try to look at it.

**Comment by ChuckBell** [comment]
Closed due to inactivity.
