### ISSUE TITLE
Seeking advice on Ethernet library

### ISSUE THREAD

**Issue by apeiris** [ChuckBell/MySQL_Connector_Arduino#138]
I am trying to connect to MySql  with ESP32 using PlatformIO, on searching for Ethernet library, I find many (109) ehternet libraries.. Should I choose a specific one or any one of those 109 libraries will work ?

**Comment by ChuckBell** [comment]
Start with the Arduino-supplied library. If that doesn't work, look at your vendor's documentation to see which library they recommend. Note that unless the library is 100% compatible with the connector, you may not be able to use it. Even so, you will have to modify the header file for the connector. Check the Wiki for more details.
