### ISSUE TITLE
Update data with dynamic value  ESP8266 

### ISSUE THREAD

**Issue by oussama415** [ChuckBell/MySQL_Connector_Arduino#139]
Hi,
Please i want to update data from a database table with a dynamic value 
I have an incrementing variable and I want to update this value in the database each time

I tried :

```
int counter ;
char UPDATE_SQL[] = "UPDATE database.table SET counter = %f WHERE id= 1";
char query2[500];

// loop()
   counter = 20;
    sprintf(query2, UPDATE_SQL, counter);
    Serial.println("Updating data energy.");
    Serial.println(query2);
    MySQL_Cursor *cur_mem7 = new MySQL_Cursor(&conn);
    cur_mem7->execute(query2);
    delete cur_mem7;
```

  I have always 0 In value !!

I need your help 
Thanks.

**Comment by ChuckBell** [comment]
Use %d  or %i, not %f. See sprintf docs.

**Comment by oussama415** [comment]
Thanks so Much, it work with %d 
Thanks.

**Comment by ChuckBell** [comment]
Closed due to inactivity. Please open a new ticket if this is still relevant.
