### ISSUE TITLE
Can't resolve hostname: db5000643147.hosting-data.io

### ISSUE THREAD

**Issue by dreeez** [ChuckBell/MySQL_Connector_Arduino#152]
My provider isn't able to give me a IP4 Address for my hostname (db5000643147.hosting-data.io), and the Arduino Library is also not able to resolve it.. Which options do I have?

**Comment by ChuckBell** [comment]
Classic read the manual answer, sorry: https://github.com/ChuckBell/MySQL_Connector_Arduino/wiki/Examples#connect-by-hostname-connect_by_hostnameino. Pay attention to the statement in the opening paragraph. This doesn't work for all networking boards/libraries. The other thing you can do is to ensure your DNS server can resolve the hostname. 

What Arduino board are you using? What shield/module?

**Comment by dreeez** [comment]
I am using an Arduino Uno Board from AZ-Delivery and an "SIM 900 GPRS/GSM Shield or GPS Module or SIM 808 or Ethernet" also from AZ-Delivery (with two 47 ohm resistors on it). The Hosting Provider also told me there was no way i could resolve the hostname to an IP. Is there still a way to get it to work, or would i need to make a workaround with an extra webserver?! :/

**Comment by ChuckBell** [comment]
If you can find a service that lets you lookup hostnames, yes, that should work. So far, I've not found any that allow CURL or http commands. If you find one, please post it here so others can try it out.

**Comment by ChuckBell** [comment]
Closed due to inactivity. Please open a new ticket if this is still relevant.
