### ISSUE TITLE
Turn Off Serial Reporting?

### ISSUE THREAD

**Issue by Endorfin35** [ChuckBell/MySQL_Connector_Arduino#157]
Even though I turned off  #Define Debug, 
some information still coming in serial port. Is there an easy way to turn it off?

**Comment by ChuckBell** [comment]
Hi,

Some of that is controlled with the WITH_SELECT definition. You can safely
ignore it, but if you need to turn it off, you can either comment out all
of the Serial.print*() statements in the connector code or alter it to
place them in a new define (maybe WITH_SILENT or some such). If you need
help, I can assist and create you a patch you can apply.

Dr. Bell

**Comment by Endorfin35** [comment]
I can block all serial.print commands in the library one by one. But, I don't have enough experiment about adding a new function to do this.

However, I do not think want to request you to make such an arrangement.

It's not that soo important. Thanks.
