### ISSUE TITLE
Unable to compile MySQL_Connector_Arduino using Arduino UNO WIFI R2

### ISSUE THREAD

**Issue by tlittle559** [ChuckBell/MySQL_Connector_Arduino#159]
Using an Arduino UNO WIFI R2 with Aduino IDE 1.8.13 and MySQL_Connector_Arduino V1.2.0 I was not able to compile the sketch "connect_wifi" or even compile "connect" with an Ethernet2 shield attached to the UNO WIFI R2.  However "connect" compiled and connected perfectly with the Ethernet2 shield attached to an Arduino UNO R3.  

The compilation error reported was an issue with resolving "Print.h" in "MySQL_Encrypt_Sha1.cpp", which in turn caused other errors.

I found (after trying many other things) that if I added "#include <Arduino.h>" at the beginning of the include list in both "MySQL_Encrypt_Sha1.cpp" and "MySQL_Encrypt_Sha1.h" the library would compile.

Of course in the sketch the "#include <WiFi.h>" changes to "#include <WiFiNINA.h>".

I have since had success with the "basic_select" and "complex_insert" examples by copying over the wifi connection block of code in place of the ethernet connection.

I hated to make this an issue since it has been solved, but it would have saved me many hours if I had been able to see this information.  Maybe it will help someone else.

**Comment by ChuckBell** [comment]
Yes, this is planned for the next release and I’ll add it to the wiki.

**Comment by ChuckBell** [comment]
Updated documentation to include this issue. Next release will include an improvement to help mitigate the issue.
