### ISSUE TITLE
Information ciphered?

### ISSUE THREAD

**Issue by VittorioEsposito** [ChuckBell/MySQL_Connector_Arduino#16]
Hi Dr. Bell,
Are queries ciphered by mysql if i connect to 3306 port with you library?

**Comment by ChuckBell** [comment]
Sorry, do you mean encrypted? No, the queries are sent clear text over the wire. The connector does not support encrypted connections.

**Comment by VittorioEsposito** [comment]
And where can i find information about mysql protocol?

**Comment by ChuckBell** [comment]
Sadly, the old client/server protocol is no longer documented. Only the new X Protocol is documented, which the connector does not support (used in MySQL 8.0 and later). If you can tell me what you're looking for, I may be able to direct you to the correct location/URL.

**Comment by VittorioEsposito** [comment]
I'm writing an exam documentation about a project that uses your connector library, and i should write something about how does it work.

**Comment by ChuckBell** [comment]
If you PM me, I'll send you some files that will help.

d r c h a r l e s b e l l at g m a i l dot c o m

**Comment by VittorioEsposito** [comment]
Sent
