### ISSUE TITLE
conn.close() doesn't close properly

### ISSUE THREAD

**Issue by hervema** [ChuckBell/MySQL_Connector_Arduino#162]
Hello,

When I would like to close an opened connection I use <conn>.close() function. 

This works, apparently, as the connection is not really closed on the server and seems to stay in a "sleep" mode, and the number of connections on the server is growing over and over again...

Is there a better way to, really, close a connection on the server ?

Thanks,

Regards,

Hervema

**Comment by hervema** [comment]
Hello,

I've found my problem.

In my code, the call to .close() function was immediately follow by a wifi.disconnect ... 

I added a delay between, delay(300), and all is working well now ! :-)

Thanks,

Regards,

Hervema

**Comment by ChuckBell** [comment]
Excellent!
