### ISSUE TITLE
Extract the type of error

### ISSUE THREAD

**Issue by quakef4** [ChuckBell/MySQL_Connector_Arduino#163]
Hello,
I would need to memorize the type of error within a variable:
Example this:
`Error: 75 = Deadlock found when trying to get lock; try restarting transaction.`
in this case, I would need to memorize the number 75 inside a variable.

Is this possible without making changes to the library?

Thanks in advance!

**Comment by ChuckBell** [comment]
Hi,

Not directly, no, but the modification isn’t difficult. You could simply write a special handler as part of parse_error_packet(), add code to execute_query(), or add a function to return the error number (best solution).

Dr. Bell

Hint (warning: not tested):

--- /Users/cbell/source/MySQL_Connector_Arduino/src/MySQL_Cursor.h	2020-09-03 15:37:28.000000000 -0400
+++ ./MySQL_Cursor.h	2021-01-04 14:04:20.000000000 -0500
@@ -79,6 +79,7 @@
     void show_results();
     int get_rows_affected() { return rows_affected; }
     int get_last_insert_id() { return last_insert_id; }
+    int get_error() { return conn->read_int(5, 2); }
 #endif
 
   private:


And in your sketch, do something like this (again, not tested):

  if (!cur.execute(query)) {
    If (cur.get_error() == 75) {
        Serial.println(“My custom error. “);
    } else {
        Serial.print(“ERROR: Wonkification in progress. Error code=“);
        Serial.println(cur.get_error());
    }
  }

**Comment by quakef4** [comment]
Yeah! it work fine!
Only correct little thing on arduino sketch:
`->`  instead of `.`
`Serial.println(cur->get_error());`
Would it be possible to add it as a modification?
Detecting the error allows you to understand if the query was sent and acquired successfully.
Correct me if I'm wrong

**Comment by ChuckBell** [comment]
On my list, yes. :)

**Comment by quakef4** [comment]
Thanks! 
To make good!
