### ISSUE TITLE
ESP32 connection issues

### ISSUE THREAD

**Issue by TETONJoshua** [ChuckBell/MySQL_Connector_Arduino#172]
Hello,
I'm trying to set up an esp32 to write data to a microsoft azure database, but I'm having a problem connecting to the database. I end up with the following unreadable error: Error: 44 = tive_passwordm+S3dXeu]sF\y7F. I specify that the connection information is correct (password, ip, user) and that the error appears when executing the following command : conn.connect(server_addr, 3306, user, password). thank you in advance if you can help me.

Used code : 
#include <WiFi.h>
#include <MySQL_Connection.h>
#include <MySQL_Cursor.h>

IPAddress server_addr();
char user[] = "";
char password[] = "";

char INSERT_SQL[] = "INSERT INTO Totems (IdTotem, Lieux) VALUES (3, 'Tomblaine')";
char ssid[] = "";
char pass[] = "";

WiFiClient client;
MySQL_Connection conn(&client);
MySQL_Cursor* cursor;

void setup()

{
  Serial.begin(115200);
  while (!Serial); 
  Serial.printf("\nConnecting to %s", ssid);
  WiFi.mode(WIFI_STA);
  WiFi.begin(ssid, pass);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  Serial.println("\nConnected to network");
  Serial.print("My IP address is: ");
  Serial.println(WiFi.localIP());

  Serial.print("Connecting to SQL...  ");
  if (conn.connect(server_addr, 3306, user, password)){
    Serial.println("OK.");
  }
  else{
    delay(2000);
    Serial.println("FAILED.");
  }
  cursor = new MySQL_Cursor(&conn);
  if (conn.connected()){
    cursor->execute(INSERT_SQL);
  }
  delay(5000);
  WiFi.disconnect();
  WiFi.mode(WIFI_OFF);
}

void loop()

{
  
}

**Comment by ChuckBell** [comment]
What version of MySQL are you using? What version of the connector?

**Comment by TETONJoshua** [comment]
I'm using the version of MySQL 5.7

**Comment by ChuckBell** [comment]
I have confirmed this is a bug in the ESP8266 v3.0 hardware code. You can revert to 2.7.4 and it will work again. Just uninstall the 3.0.0 and install the 2.7.4.

**Comment by Bjorn-J** [comment]
The ESP8266 core was recently updated to 3.0.1 but this bug is still present. Back to 2.7.4 again. Does anybody know which issue # this relates to at ESP8266? I assume it has been reported. I don't know what the actual problem is so it is hard to search for it.
