### ISSUE TITLE
missing Option to use Parameter sslConnection=true ?

### ISSUE THREAD

**Issue by tioannidis** [ChuckBell/MySQL_Connector_Arduino#174]
Hi
below an example of a jdbc connection string to an IBM Cloud DB2 isntance.

"jdbc:db2://ibmURLxxxx.databases.appdomain.cloud:32536/bludb:user=<userid>;password=<your_password>;sslConnection=true;"

For the connection i need to use the parameter "sslConnection=true;"
I tryed to connect with inserting the sslConnection Parameter in the default_db char but I get an timeout
char hostname[] = "ibmURLxxxx.databases.appdomain.cloud";
char user[] = "???";
char db2key[] = "???";
char default_db[] = "bludb:sslConnection=true"

Its any other possibility to use the sslConnection Parameter?

**Comment by ChuckBell** [comment]
Hi,

No, the connector does not support SSL connections. It is far too simple
(small) for such a feature. It can be added, but at the cost of hardware
exclusion due to the larger code and memory size.

Also, I should point out the connector only works with Oracle MySQL.

Dr. Bell

**Comment by tioannidis** [comment]
thx for the answer
