### ISSUE TITLE
Waiting for mysql connection return 

### ISSUE THREAD

**Issue by renandamaia** [ChuckBell/MySQL_Connector_Arduino#175]
Hello Mr ChuckBell,
I'm facing some connection problems with my database that sometimes becomes unavailable, either because of wifi drop or MySQL database availability.

Is there any function to store the readings and wait for the database to be available and then run the query?

**Comment by ChuckBell** [comment]
Hi,

Sadly, no. But you can write one! You need only a way to store the data or
the queries then when you next get a good connection, issue the queued
queries.

This has been done before by myself and others. The only downside is if
your sampling rate is too fast, the time it takes to process the queue can
result in missed sensor readings.

You should also check the status of your wifi as part of the solution.

Finally, look over the wiki for an example of how to handle network and FB
system drops.

Dr. Bell

**Comment by renandamaia** [comment]
Thanks for the feedback

**Comment by ChuckBell** [comment]
If you create a solution, please share in the issue. If not, please kindly close the issue. Thanks.
