### ISSUE TITLE
help -- How to read config from a String

### ISSUE THREAD

**Issue by wilson405** [ChuckBell/MySQL_Connector_Arduino#179]
hi,
everything works perfectly, I just need a help, I need  user and password, to be read from a string, because I will store it in Spiffs, can someone help me.

example :

// database user and password
char user[] = **here variable type String** ;             
char password[] = **here variable type String**;

**Comment by ChuckBell** [comment]
Hi. Can you be more specific? Maybe post a code snippet so I can see what you want to do? Otherwise, you may want to look at the sample sketches that show how to use a format string and sprintf() to fill in values.
