### ISSUE TITLE
Query Result wrong why??

### ISSUE THREAD

**Issue by yonathan28** [ChuckBell/MySQL_Connector_Arduino#18]
I try got result query from some result in rfid action this my sample try code
`unsigned long getID(){
  if ( ! mfrc522.PICC_ReadCardSerial()) { //Since a PICC placed get Serial and continue
    return -1;
  }
  unsigned long hex_num;
  hex_num =  mfrc522.uid.uidByte[0] << 24;
  hex_num += mfrc522.uid.uidByte[1] << 16;
  hex_num += mfrc522.uid.uidByte[2] <<  8;
  hex_num += mfrc522.uid.uidByte[3];
  mfrc522.PICC_HaltA(); // Stop reading
  return hex_num;

}
void loop() 
{
  if (mfrc522.PICC_IsNewCardPresent()) 
  {
    long head_count = 0;
    row_values *row = NULL;
    unsigned long uid = getID();
    if(uid != -1){
    Serial.print("Card detected, UID: "); Serial.println(uid);
    char query[] = "SELECT nominal FROM tescard.data_kartu WHERE no_kartu = 'uid' ";
    MySQL_Connection conn((Client *)&client);
    row_values *row = NULL;
  long head_count = 0;
  delay(1000);
  Serial.println("1) Demonstrating using a cursor dynamically allocated.");
  MySQL_Cursor *cur_mem = new MySQL_Cursor(&conn);
  MySQL_Cursor cur = MySQL_Cursor(&conn);
  cur_mem->execute(query);
  column_names *columns = cur_mem->get_columns();
  do {
    row = cur_mem->get_next_row();
    if (row != NULL) {
      head_count = atol(row->values[0]);
    }
  } while (row != NULL);
  delete cur_mem;
  Serial.print("  NYC pop = ");
  Serial.println(head_count);
  delay(500);

  Serial.println("2) Demonstrating using a local, global cursor.");
  // Execute the query
  cur.execute(query);
  // Fetch the columns (required) but we don't use them.
  cur.get_columns();
  // Read the row (we are only expecting the one)
  do {
    row = cur.get_next_row();
    if (row != NULL) {
      head_count = atol(row->values[0]);
    }
  } while (row != NULL);
  // Now we close the cursor to free any memory
  cur.close();

  // Show the result but this time do some math on it
  Serial.print("  NYC pop = ");
  Serial.println(head_count);
  Serial.print("  NYC pop increased by 12 = ");
  Serial.println(head_count+12);
    }
  }
  
  `

from my code the result NYC pop = 0
but if i use this code `char query[] = "SELECT nominal FROM tescard.data_kartu WHERE no_kartu = '1131778731' ";`
that show the coreect result where my code is wrong??

**Comment by ChuckBell** [comment]
You're not substituting the value for the where clause. The query you are executing is literally:

SELECT nominal FROM tescard.data_kartu WHERE no_kartu = 'uid'

Check the reference manual for how to build a query string with parameters. Hint: see the example sketch entitled "complex_select". You need to use that technique.
