### ISSUE TITLE
How to add sslConnection?

### ISSUE THREAD

**Issue by OMARQUES** [ChuckBell/MySQL_Connector_Arduino#180]
Hi
I'm using this mysql connector for a project with the Rpi Pico, it works great, but i'm having trouble to connect to a local Mysql server. I did a few tests, it works both in Arduino Pro Mini and Rpi Pico with mysql_native_password on the Mysql user. But i can't use this on the production server, is there a way to add the SSL in any way?

**Comment by ChuckBell** [comment]
Not with the connector directly, no. There simply isn't enough memory to accommodate the extra code that would be needed to create SSL connections. 

However, I have wanted to experiment with a crypto module that has such capabilities. If you are inclined to tinker with the code, you may be able to adapt a crypto module for use with the connector to provide an SSL connection. But I must warn that this could be a very intensive code change. You're welcome to try it!
