### ISSUE TITLE
Only executing get_columns() twice leads to a result...

### ISSUE THREAD

**Issue by grenelt** [ChuckBell/MySQL_Connector_Arduino#19]
i encountered a weird problem here - i'm not sure if it is an issue, but i checked that i have the latest library files and no memory issues. I'm on the latest Arduino-IDE (1.8.3). I also tried several selects, simpler ones - but with no change at all.

For starters the simplyfied code:
```
const char PROGMEM DBCommandStr[] = "use hsd; select sw.group, sw.switch, sw_rules.lbound, sw_rules.ubound, sw_rules.type, "
                                    "(SELECT sensor_data.data FROM sensor_data WHERE sensor_data.ID = sw_rules.sensor_ID AND sensor_data.channel = sw_rules.channel_ID ORDER BY TIME DESC LIMIT 1) as currentValue "
                                    "from sw_schedules RIGHT JOIN sw_rules ON sw_rules.ID = sw_schedules.rule LEFT JOIN sw ON sw.ID = sw_rules.switch_ID "
                                    "where state = 1 AND ((1 << weekday(now()) & day) > 0) AND IF (TIMEDIFF(end, start) > 0, current_time() between start AND end, current_time() > start OR current_time() < end);";

void query() {

    while (!conn.connected()) {
      connectDB();
    }
    MySQL_Cursor *cur_mem = new MySQL_Cursor(&conn);
    cur_mem->execute(DBCommandStr, true);
    
     column_names *cols = cur_mem->get_columns();

    cur_mem->show_results();

    delete cur_mem;
}
```

This one works with the following (correct) output:
```
DB...Connected to server version 5.5.5-10.0.23-MariaDB-0ubuntu0.15.04.1
group,switch,lbound,ubound,type,currentValue
00001,00001,17,18,inner,23.6
00001,00010,19,20,inner,22.5
2 rows in result.
```

Now im leaving out the initial get_columns() - although the show_results() does the get_columns() itself:
```
void query() {

    while (!conn.connected()) {
      connectDB();
    }
    MySQL_Cursor *cur_mem = new MySQL_Cursor(&conn);
    cur_mem->execute(DBCommandStr, true);
    
    cur_mem->show_results();

    delete cur_mem;
}
```
... that brings me to here:
```
DB...Connected to server version 5.5.5-10.0.23-MariaDB-0ubuntu0.15.04.1
6 rows in result.
Error: 29 = 0011718inner23.6.
Bad mojo. EOF found reading column header.
```

And now i'm changing to the sample code:
```
void query() {

    while (!conn.connected()) {
      connectDB();
    }
    MySQL_Cursor *cur_mem = new MySQL_Cursor(&conn);
    cur_mem->execute(DBCommandStr, true);
    
     column_names *cols = cur_mem->get_columns();

     row_values *row = NULL;

    for (int f = 0; f < cols->num_fields; f++) {
      Serial.print(cols->fields[f]->name);
      if (f < cols->num_fields - 1) {
        Serial.print(", ");
      }
    }
    Serial.println();


    do {
      row = cur_mem->get_next_row();
      if (row != NULL) {
        for (int f = 0; f < 5; f++) {
          Serial.print(row->values[f]);
          Serial.print(" ");

        }
        Serial.println();
      }
    } while (row != NULL);

    delete cur_mem;
}
```

An now it's getting really wild - and the result takes a lot longer (maybe because of a lot of garbage). I shortened it a lot here....
```
DB...Connected to server version 5.5.5-10.0.23-MariaDB-0ubuntu0.15.04.1
Bad mojo. EOF found reading column header.
, , , , , , , 10.0.23-MariaDB-0ubuntu0.15, , , , , , , ⸮, , , , , , , ⸮⸮K⸮⸮⸮⸮⸮o⸮⸮⸮⸮⸮⸮⸮/⸮⸮⸮⸮n'=⸮~ׯ⸮⸮c⸮;⸮.⸮|U⸮⸮#⸮⸮⸮⸮g⸮⸮_v⸮⸮⸮⸮⸮⸮|w⸮M⸮⸮⸮O⸮⸮⸮P}=⸮⸮⸮⸮i⸮⸮y⸮⸮⸮⸮⸮⸮	J⸮⸮⸮⸮⸮⸮⸮⸮⸮z⸮_⸮⸮⸮⸮⸮⸮
⸮⸮⸮⸮o⸮⸮⸮m⸮l?⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮ח⸮⸮⸮v⸮⸮j~⸮⸮?⸮⸮⸮O⸮߅⸮⸮⸮⸮-⸮⸮?s⸮⸮⸮⸮^⸮⸮⸮7⸮\ͪߪ_⸮⸮⸮&⸮e⸮v⸮⸮A⸮⸮⸮⸮⸮U⸮[o⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮d⸮⸮~⸮⸮V⸮5⸮⸮⸮⸮Ο⸮+⸮{Ͽ⸮5⸮⸮⸮⸮⸮gܵ⸮⸮⸮⸮⸮⸮⸮⸮~⸮v⸮⸮⸮~⸮⸮
⸮⸮~⸮⸮⸮⸮5}?~/⸮⸮/]⸮۝⸮Ͼv⸮⸮τPs⸮w]⸮a⸮⸮⸮⸮⸮d?t⸮O⸮⸮⸮Rf⸮z⸮⸮⸮5ѿ⸮⸮⸮[⸮{⸮⸮⸮⸮⸮⸮}*}⸮ظoSZvw⸮⸮⸮⸮⸮g⸮⸮sǍe{⸮Ov⸮'~=U⸮⸮⸮⸮_⸮ձ^⸮_.⸮⸮⸮⸮ǟ⸮⸮⸮
```

First i tried it on an Uno but i'm aware of memory consumption (from other projects... ;) ) so i changed to a Mega for more SRAM - but the problems are still the same.

But now i'm in a rush - why not doubling the get_columns() in general:
```
void query() {

    while (!conn.connected()) {
      connectDB();
    }
    MySQL_Cursor *cur_mem = new MySQL_Cursor(&conn);
    cur_mem->execute(DBCommandStr, true);
    
     column_names *cols = cur_mem->get_columns();
     cols = cur_mem->get_columns();

     row_values *row = NULL;

    for (int f = 0; f < cols->num_fields; f++) {
      Serial.print(cols->fields[f]->name);
      if (f < cols->num_fields - 1) {
        Serial.print(", ");
      }
    }
    Serial.println();


    do {
      row = cur_mem->get_next_row();
      if (row != NULL) {
        for (int f = 0; f < cols->num_fields; f++) {
          Serial.print(row->values[f]);
          Serial.print(" ");

        }
        Serial.println();
      }
    } while (row != NULL);

    delete cur_mem;
}
```

The eagle has landed:
```
DB...Connected to server version 5.5.5-10.0.23-MariaDB-0ubuntu0.15.04.1
group, switch, lbound, ubound, type, currentValue
00001 00001 17 18 inner 23.6 
00001 00010 19 20 inner 22.6 
```

... but i'm a little bit puzzled. Maybe the issue is, that one of the get_columns() (the first called?) isn't executed properly.

**Comment by ChuckBell** [comment]
Hi,

It must have something to do with the query and how MySQL is returning results.

I see in your first example you are indeed doubling the get_columns() call since show_results() calls it too. It is likely there is an unexpected packet being sent that the first get_columns() is handling (moving past).

This warrants further investigation in how MySQL is returning the results from a complex join. 

I am glad you found a work around in the meantime.

Chuck

**Comment by ChuckBell** [comment]
Ok, I think I see it. Try removing the Use hsd statement. That is, modify the query to specify the database and don’t use the USE command.

**Comment by ChuckBell** [comment]
Confirmed: the problem is the USE command. Remove that and you won’t need the two get_columns().

**Comment by grenelt** [comment]
Hi Chuck,

thank you very much - for your work in general and in special.

In theory, you're right. In practice i have to "USE" because otherwise i get an error 29 "No database selected".  Queries from other device (PC, ESP8266 with an old connector version) work without the explicit "USE".
So i tried separating the USE like this:
```
void setup() {
connectDB();
MySQL_Cursor *cur_mem_use = new MySQL_Cursor(&conn);
cur_mem_use->execute(DBCommandStrUse, true);
delete cur_mem_use;
}

void loop() {
MySQL_Cursor *cur_mem_query = new MySQL_Cursor(&conn);
cur_mem_query ->execute(DBCommandStrQuery , true);
column_names *cols = cur_mem->get_columns();
.
.
.
delete cur_mem_query ;
}
```
Now: After the first query i get an Error 24 = Unknown command after some seconds after the first query. Then the connector locks up.

Interesting here: If i try to read columns after issueing the USE in setup, the connector locks up instant.

The only way i get this working ist to insert a complete USE query block before each single query - or to integrate it and read the colums twice... Both not really nice solutions...

The issue maybe is that the connector does something that prevents MariaDB (in my case) to select the default database in every case. And i can't see the fault in my configuration - which doesn't mean there is no fault. ;) 

I changed also to the most current ethernet-library but this doesn't change anything. I connect via an W5100 shield.

**Comment by ChuckBell** [comment]
Hi,

Well, there are two things here.

First, you must qualify your query with Db.tbl to avoid requiring the USE command. My tests show this is always the case with MySQL.

Second, the connector is designed to work with MySQL. Any other form/variant of MySQL is not officially supported. If you are having problems with another variant of MySQL, that could explain the problems you are seeing. 

I would suggest changing your query to use the proper notation to remove the USE statement and use Oracle’s MySQL.

Dr. Bell
