### ISSUE TITLE
ESP32 / Expressif32 v5.2.0 / Connection problem

### ISSUE THREAD

**Issue by hervema** [ChuckBell/MySQL_Connector_Arduino#199]
Hello. I have been using your excellent library for several years in a program on an ESP32 and the Expressif32 in version 3.4.0, and everything works perfectly. However, I had to upgrade the Expressif32 version to 5.2.0 and for some reason I can't figure out, a simple connection to the MySQL server no longer works! I also tested with version 4.4.0, same connection problem. Only version 3.x.x works. Is there any evolution in the latest Expressif32 versions that I should know about to get around this problem? I would appreciate it. :-)

I'm using version 1.2.0 of your library.

Thanks,

Regards,

Hervema

**Comment by BMerz** [comment]
There is a bug in the 1.2.0 library when installed in Arduino. Changing these two lines in this commit made my day :-)
https://github.com/ChuckBell/MySQL_Connector_Arduino/pull/177/commits/da48660b9b60cd717e856ed503bcc55ed91d755a

**Comment by hervema** [comment]
I don't get why exactly, but this save my day also on my ESP32 !! :-) great. Thanks a lot BMerz !!!
