### ISSUE TITLE
Problem using with Ethernet2 Library

### ISSUE THREAD

**Issue by mdilger** [ChuckBell/MySQL_Connector_Arduino#20]
Hi,

I am wanting to use the Ethernet2 library as the shield I have has the W5500 chip.

But each time I add the MySQL connector library it automatically adds the (original) Ethernet library.  I think it is due to the fact that **MySQL_Packet.h** has the following line:

`#include <Ethernet.h>`

I don't see this referenced anywhere else in the other MySQL Connector library files.

Is this line necessary, given that it is included in the main code  (in my case `#include <Ethernet2.h`>)?

Cheers,
Mike

**Comment by ChuckBell** [comment]
Hi,

Yes, it is necessary. Just change it to Ethernet2. 

Dr. Bell

**Comment by mdilger** [comment]
Thanks, will do.
Cheers,
Mike
