### ISSUE TITLE
When ESP32 connects to MYSQL, the program will stop

### ISSUE THREAD

**Issue by rdot-lee** [ChuckBell/MySQL_Connector_Arduino#200]
When connecting to the database again, the program will be stuck at 
conn.connect() > sendAuthenticationPacket() > scramble_password() >  Sha1.print(password), fall into the loop after entering

**Comment by rdot-lee** [comment]
like this：

![image](https://user-images.githubusercontent.com/83214802/208464117-380afe6f-8fe1-4d1e-940e-31cfd3240c03.png)

**Comment by moosepr** [comment]
Im having the exact same issue, I have traced it to the Sha1.print(password); line

I am also using an esp32!! and using the standard example for wifi connection

**Comment by moosepr** [comment]
heh

just looking through closed issues that mention the esp32 and came accross this commit

https://github.com/ChuckBell/MySQL_Connector_Arduino/commit/da48660b9b60cd717e856ed503bcc55ed91d755a

it adds some returns into the sha1 write functions. i made the same changes to my local files and everything now works!!

**Comment by rdot-lee** [comment]
thanks

The issue was fixed to resolve.
