### ISSUE TITLE
Connection denied

### ISSUE THREAD

**Issue by MartinDor** [ChuckBell/MySQL_Connector_Arduino#214]
To connect to a database (Mariadb 10), I use my stm32 and a PHY the W5500. Currently, I can create a socket and then connect to the server's IP. However when I start sending the authentication packet I get the error message: "mysql access denied for user 'user'@'192. . . ' (using password yes)". The code I use to get authenitcation is from this library which I have rewritten for the STM32. In addition, I also tried sending the same message without hasing. With this, I get the error message "handshake not correct". How exactly can I solve this error? The database has the following authentication plugins:

Mysql_native_password Native MySQL authentication 2.1 R.J.Silk, Sergei Golubchik GPL
Mysql_old_password Old MySQL-4.0 authentication 2.1 R.J.Silk, Sergei Golubchik GPL
uUnix_socket Unix Socket-based authentication 2.1 Sergei Golubchik GPL

**Comment by ChuckBell** [comment]
Hi. See the wiki for troubleshooting connection issues as you describe. Hint: “users” and permissions in MySQL combine host+ip. Hint: see the (less secure) “%” host option.

**Comment by MartinDor** [comment]
Hi @ChuckBell, 
I have already looked at the wiki. Everything seems to be correct.
After further investigation, I found out that I rewrote a piece of code incorrectly. Something with pointers and casting. Luckily, it works now! Thanks for your response!
