### ISSUE TITLE
how to install MySQL_Connector_Arduino into github workflow to auto build?

### ISSUE THREAD

**Issue by everschen** [ChuckBell/MySQL_Connector_Arduino#221]
Running command: /home/runner/bin/arduino-cli lib install MySQL_Connector_Arduino 
   Error installing MySQL_Connector_Arduino: Library 'MySQL_Connector_Arduino' not found

**Comment by ChuckBell** [comment]
Hello. That is not the name. Use quotes:

./arduino-cli lib install "MySQL Connector Arduino"
