### ISSUE TITLE
Failing to compile for ESP8266. Even the Example skatches.

### ISSUE THREAD

**Issue by Gabeki17** [ChuckBell/MySQL_Connector_Arduino#224]
ESP8266 version is: 3.1.2
Mysql_Connector_Arduino version is: 1.2.0

It looks the new ESP lib collection is always expecting returns.

Just tried one example sketch and I think the below addition of two `return 0;` to "MySQL_Encrypt_Sha1.cpp" is solving.

```
size_t Encrypt_SHA1::write(uint8_t data) {
  ++byteCount;
  addUncounted(data);
  return 0;
}

size_t Encrypt_SHA1::write(uint8_t* data, int length) {
  for (int i=0; i<length; i++) {
    write(data[i]);
  }
  return 0;
}
```
Unfortunately, this is only part of the issue.
Is failing to get connected.
Refering on athentication issue, however I am 100% confident on the credentials and server access settings.

Thank you for your attention!

With kind regards,
Gábor

**Comment by ChuckBell** [comment]
See: https://github.com/ChuckBell/MySQL_Connector_Arduino/commit/da48660b9b60cd717e856ed503bcc55ed91d755a
