### ISSUE TITLE
very long response time in INSERT with Wemos D1 mini esp8266

### ISSUE THREAD

**Issue by joseagarciac** [ChuckBell/MySQL_Connector_Arduino#23]
Good day Dr Bell, excellent library, I use it in arduino equipment and it works wonderfully, I currently have a wemos d1 mini working with this library, I can connect to the database without problems, I can even INSERT data, the problem is that It takes up to 10 seconds to respond to each of the INSERT, could it be doing something wrong in the code? (in an arduino Mega the same code works without problems), grateful for your help in this case.

`   Serial.println("Verificando Conexion...");
    if (conn.connected()) {
      Serial.println("Conectado a la Base de Datos MySQL.");
      delay(500);
      Serial.println("Escribiendo a la Base de Datos MySQL.");
      // Initiate the query class instance
      MySQL_Cursor *cur_mem = new MySQL_Cursor(&conn);
      cur_mem->execute("USE iotco;");

     Date = String(dateTime.year) + "-" + String(dateTime.month) + "-" + String(dateTime.day) + " " + String(dateTime.hour) + ":" + String(dateTime.minute) + ":" + String(dateTime.second);
      char otro [Date.length()+1];
      Date.toCharArray(otro, Date.length()+1);
      const char* Fecha= otro; 
      
    dtostrf(humi, 1, 1, humidity);
    sprintf(query, INSERT_DATA, humidity, IDhumidity, Fecha);
    Serial.println(query);
    // Execute the query
    cur_mem->execute(query);
    Serial.println("Humedad Guardada en MySQL.");

    dtostrf(temp, 1, 1, temperature);
    sprintf(query, INSERT_DATA, temperature, IDtemperature, Fecha);
    Serial.println(query);
    // Execute the query
    cur_mem->execute(query);
    delete cur_mem;
    Serial.println("Temperatura Guardada en MySQL.");
    num_fails = 0;                 // reset failures
    }
    else {
    Serial.println("Conectando a la Base de Datos MySQL...");
    if (conn.connect(server_addr, 3306, user, password)) {
      delay(500);
    } else {
      num_fails++;
      Serial.println("Conexion Fallida!");
      if (num_fails == MAX_FAILED_CONNECTS) {
        Serial.println("Ok, that's it. I'm outta here. Rebooting...");
        delay(1000);
        // Here we tell the Arduino to reboot by redirecting the instruction
        // pointer to the "top" or position 0. This is a soft reset and may
        // not solve all hardware-related lockups.
           ESP.restart();
      }
    }
   }`

**Comment by ChuckBell** [comment]
Hi,

I do not see anything in your sketch to suggest a cause for the delay. 
However, in my experience, the ESP wifi modules are slower. You may be 
able to tweak the connector library a bit by reducing the timeout 
values, but I don't recommend that because it can be unstable for slower 
boards.

Other than that, I don't see the INSERT statement, but it appears you're 
making two passes to save the data. You can reduce query time if you 
used a single INSERT and saved both data elements in the same row.

Dr. Bell

**Comment by xavisosa** [comment]
Good evening, a consultation, the char * INSERT_DATA how is this formed ??

sprintf(query, INSERT_DATA, humidity, IDhumidity, Fecha);

so that I can add date and time, since I can not record in the database, in a DATE field, thanks

**Comment by ChuckBell** [comment]
Why do you not want to use a TIMESTAMP field? It works very well. 

Otherwise, you use the sprintf() method with the INSERT_DATA setup as a format string. See the example sketches and documentation for examples.
