### ISSUE TITLE
basic insert not working

### ISSUE THREAD

**Issue by roszaidah** [ChuckBell/MySQL_Connector_Arduino#24]
hello, i try to run your code given in basic insert..the code can compile but there is no data inserted in the database, what is the problem?i am creating the database, table in phpmyadmin

**Comment by copterino** [comment]
Have you tried to insert data using any sql client program? There is a possibility, that your query is incorrect.

**Comment by roszaidah** [comment]
I inserted it using sql code and its working.. Meaning that the query is
correct

**Comment by copterino** [comment]
Than I propose you to Serial.print() every sql query and check its correctness there.
If everything is correct paste your code here and we will try to investigate.

**Comment by roszaidah** [comment]
My apache server not use port 80 because has its been use. So i am using
port 8012, it is affect to the database server?
