### ISSUE TITLE
ESP32 is not work.

### ISSUE THREAD

**Issue by kyumdlab** [ChuckBell/MySQL_Connector_Arduino#26]
ESP32 is not work, can you support ESP32?
Thank you!!

**Comment by ChuckBell** [comment]
Yes and no. It's not the connector that is the problem, it is the 
supporting networking code you use for the ESP chip. The connector code 
was written to sit on top and make use of the Ethernet/WiFi classes. 
Most networking classes made for the ESP chips were implemented differently.

Yes:

The ESP-related chips are supported under very specific conditions. The 
library you use in place of the Ethernet/WiFi class *must* be 100% 
compatible with the Arduino Ethernet/WiFi classes.

No:

Most ESP libraries are custom libraries have some odd quirk or 
difference in how the lower-level networking classes work making it 
incompatible with the connector. Sadly, I've not had much luck with 
Ethernet/WiFi libraries for the ESP modules.

Postlude:

The ESP networking library that I use has been replaced with a version 
that is no longer compatible. If you PM me, I will send you the older code.

**Comment by ChuckBell** [comment]
This one shows some promise: https://github.com/ekstrand/ESP8266wifi. No 
guarantees, though.

**Comment by kyumdlab** [comment]
Thank you for your reply!

**Comment by kyumdlab** [comment]
I modified `MySQL_Packet.h`.
Change code to:
```
#ifndef MYSQL_PACKET_H
#define MYSQL_PACKET_H

#ifdef ESP32
#include <WiFi.h>
#else
#include <Ethernet.h>
#endif
```

Now ESP32 is work!  
Thank!
