### ISSUE TITLE
Minor misplaced curly bracket in Manual.

### ISSUE THREAD

**Issue by nanopete2** [ChuckBell/MySQL_Connector_Arduino#3]
Hi, this is a great connector, thank you very much!

In the Reboot Fix section I think there is a misplaced end curly bracket, it has to be moved up to right after `num_fails++;`

Best regards
Peter

**Comment by ChuckBell** [comment]
It should be this:

void loop() {  
  delay(1000);
  if (conn.connected()) {
    // do something
    num_fails = 0;
  } else {
    conn.close();
    Serial.println("Connecting...");
    if (conn.connect(server_addr, 3306, user, password)) {
      delay(500);
      Serial.println("Successful reconnect!");
    } else {
      num_fails++;
      if (num_fails == MAX_FAILED_CONNECTS) {
        Serial.println("Ok, that's it. I'm outta here. Rebooting...");
        delay(2000);
        soft_reset();
      }
    }
  }
}

Will fix it in the next release.
