### ISSUE TITLE
basic_insert_esp8266 causes error before setup() "ets Jan 8 2013,rst cause:2, boot mode:(3,6)"

### ISSUE THREAD

**Issue by miho** [ChuckBell/MySQL_Connector_Arduino#39]
The basic_insert_esp8266 sample causes a strange error on nodemcu devices ("new V3", based on CH340G). Other devices might be affected as well. The error happens **before** executing the `setup()` function.

**Serial Output:**

```
ets Jan 8 2013,rst cause:2, boot mode:(3,6)

load 0x40100000, len 28740, room 16 
tail 4
```

**Comment by ChuckBell** [comment]
Closed due to inactivity. Please open a new ticket if this is still relevant.
