### ISSUE TITLE
Stuck at Connecting to SQL ....

### ISSUE THREAD

**Issue by ericangwyn** [ChuckBell/MySQL_Connector_Arduino#41]
when i try to start the code below my nodemcu can connect to network already got IP and when it get into the connecting to sql the process just stop. Can someone figure why ? ,im using xampp phpmyadmin as database

#include <ESP8266WiFi.h>           // Use this for WiFi instead of Ethernet.h
#include <MySQL_Connection.h>
#include <MySQL_Cursor.h>

IPAddress server_addr(192, 168, 1, 100); // IP of the MySQL *server* here
char user[] = "root";              // MySQL user login username
char password[] = "";        // MySQL user login password

// Sample query
char INSERT_SQL[] = "INSERT INTO test_arduino.hello_arduino (message) VALUES ('Hello, Arduino!')";

// WiFi card example
char ssid[] = "x";         // your SSID
char pass[] = "x";     // your SSID Password

WiFiClient client;                 // Use this for WiFi instead of EthernetClient
MySQL_Connection conn(&client);
MySQL_Cursor* cursor;

void setup()
{
  Serial.begin(115200);
  while (!Serial); // wait for serial port to connect. Needed for Leonardo only

  // Begin WiFi section
  Serial.printf("\nConnecting to %s", ssid);
  WiFi.begin(ssid, pass);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  // print out info about the connection:
  Serial.println("\nConnected to network");
  Serial.print("My IP address is: ");
  Serial.println(WiFi.localIP());

  Serial.print("Connecting to SQL...  ");
  if (conn.connect(server_addr, 3306, user, password))
    Serial.println("OK.");
  else
    Serial.println("FAILED.");

  // create MySQL cursor object
  cursor = new MySQL_Cursor(&conn);
}

void loop()
{
  if (conn.connected())
    cursor->execute(INSERT_SQL);

  delay(5000);
}

**Comment by ChuckBell** [comment]
Did you modify the connect replacing Ethernet.h with the ESPWifi header
file!

**Comment by squallus** [comment]
XAMP uses MariaDB not original OracleMySQL, i have an similar issue, maybe this is the problem.
Lets hope there is an solution to this.

**Comment by ChuckBell** [comment]
Correct. The connectir does not work with anything other than Oracle’s
MySQL. Your only option is to uninstall the existing variant and install
MySQL. For best results, install MySQL 5.7. Version 8.0 will work but you
must enable the legacy password encryption.

**Comment by StoneAgeSkillz** [comment]
Had the same problem, permission problem. Added user permissions to mysql and it works now.

**Comment by ChuckBell** [comment]
Can we close this issue?

**Comment by beicnet** [comment]
@ChuckBell Can you maybe add support for MariaDB? Thanks! 😉
