### ISSUE TITLE
Compile error "no return statement" compiling for ESP32 board

### ISSUE THREAD

**Issue by topdancer** [ChuckBell/MySQL_Connector_Arduino#47]
Hi,

I am going to use the connector library on a ESP32 dev board. When trying to compile the "basic_insert_esp8266" example  I got two compile errors:
"Documents/Arduino/libraries/MySQL_Connector_Arduino/src/MySQL_Encrypt_Sha1.cpp:89:1: error: no return statement in function returning non-void [-Werror=return-type]", this for for lines 89 and 95.

Before compiling, in the esp8266 example I only replaced the include "ESP8266WiFi.h"  with the (ESP32) "WiFi.h" and I was using the connector version 1.2.0a (on a side note, all the header files still show version 1.1.1a?). The rest of the example sketch was not modified.

When I add a " return 0;" in both instances of the code no compile error is thrown.

Does anybody know why compiling fails and if this addition is correct?

Thanks, 
Kurt

**Comment by ChuckBell** [comment]
Certain compilers are more strict in checking for return in functions. It is fine to add "return;" to the end of each function. I do not have an ESP32 board to check, but I am certain this won't cause you any problems. The 1.2.0a is a merge of contributed code with improvements for the ESP boards. the next release will be focused on improving the documentation.

**Comment by topdancer** [comment]
Thanks Chuck!
