### ISSUE TITLE
how can i test de result?

### ISSUE THREAD

**Issue by fgaliazzo** [ChuckBell/MySQL_Connector_Arduino#50]
Hi, 
i would like to know how can i test the command, for example:

```
      MySQL_Cursor *cur_mem = new MySQL_Cursor(&conn);
     if (cur_mem->execute(QUERIE_INSERT))
       return true;
    else 
      return false;;
```
tks

**Comment by ChuckBell** [comment]
I don't know what you mean. This tool is for reporting issues with the connector. This seems like you're asking for help on how to write a query. Please try posting a more complete question on https://forums.mysql.com/list.php?175.
