### ISSUE TITLE
Works with MariaDB?

### ISSUE THREAD

**Issue by ba58smith** [ChuckBell/MySQL_Connector_Arduino#53]
Dr. Bell,

I was thrilled to find your project - looks like exactly what I need. But I just bought a Raspberry Pi 3 to use as my db server, and I've decided to use MariaDB instead of MySQL, since that's what they're including with Raspbian now. Everything I've read about MariaDB says it's 100% compatible with MySQL, so I'm hoping MySQL_Connector_Arduino will work with it. Do you have any knowledge of this, and if not, do you have any reason to suspect it might not?

Thanks so much!

Brian Smith

**Comment by ChuckBell** [comment]
I do have experience in this area. There are minor differences that make the 100% claim subject to interpretation. For example, the connector was written to work with MySQL from Oracle. It is not guaranteed to work with other variants. If you want to ensure success, you should use MySQL from Oracle. Also, I offer support only for Oracle MySQL. PM me if you need further advice or help getting MySQL on the Raspberry Pi. d r c h a r l e s b e l l at g m a i l dot c o m
