### ISSUE TITLE
Packet error.

### ISSUE THREAD

**Issue by fgaliazzo** [ChuckBell/MySQL_Connector_Arduino#54]
my code runs fine, until I get this error, so my arduino stop working

[WiFiEsp] Connecting to xx.xxx.xxx.xxx
Connected to server version 5.5.5-10.1.29
Packet error.

I suggest a timeout or a new retry

tks

**Comment by ChuckBell** [comment]
The version number printed from your post appears to be from a non-Oracle
variant of MySQL. Please confirm.

**Comment by ChuckBell** [comment]
The version number you show in your output is indeed from a non-Oracle variant of MySQL. I am sorry, but the connector was designed specifically for use with the Oracle MySQL database system. It is neither guaranteed nor supported for use on other variants.
