### ISSUE TITLE
Compile error when combining AsyncMttClient with mySQL

### ISSUE THREAD

**Issue by topdancer** [ChuckBell/MySQL_Connector_Arduino#56]
Hi,

I am struggling with combining MQTT with mySQL connector into a ESP8266 sketch.

I am starting with the „FullyFeatured-ESP8266“ example coming with the „AsyncMqttClient“  library from Marvin Roger, see here on Github: https://github.com/marvinroger/async-mqtt-client.

I can compile it without any error.

When I add:
#include <MySQL_Connection.h>
#include <MySQL_Cursor.h>

the compiler throws a compile error:

„In file included from /Applications/Arduino.app/Contents/Java/libraries/WiFi/src/utility/wifi_drv.h:26:0,
                 from /Applications/Arduino.app/Contents/Java/libraries/WiFi/src/WiFiUdp.cpp:26:
/Documents/Arduino/hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/WiFiUdp.h:28:0: note: this is the location of the previous definition
 #define UDP_TX_PACKET_MAX_SIZE 8192
 ^
In file included from /Applications/Arduino.app/Contents/Java/libraries/WiFi/src/WiFiUdp.cpp:29:0:
/Applications/Arduino.app/Contents/Java/libraries/WiFi/src/WiFiUdp.h:27:7: error: redefinition of 'class WiFiUDP'
 class WiFiUDP : public UDP {
       ^
In file included from /Applications/Arduino.app/Contents/Java/libraries/WiFi/src/utility/wifi_drv.h:26:0,
                 from /Applications/Arduino.app/Contents/Java/libraries/WiFi/src/WiFiUdp.cpp:26:
/Documents/Arduino/hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/WiFiUdp.h:32:7: error: previous definition of 'class WiFiUDP'
 class WiFiUDP : public UDP, public SList<WiFiUDP> {„ 

and more errors …

MySQL_Packet.h refers to the <WiFi.h> library (contained in Arduino IDE) which seems to conflict with <ESP8266WiFi.h> library, both containing a WiFiUDP.h file.
Removing the WiFi library from Arduino IDE creates additional errors.

How can I resolve this issue?

Any hint is welcome.

Thanks,
Kurt

**Comment by topdancer** [comment]
I am just seeing that exactly the same happens with the "mqtt-ESP8266" example from the well known  PubSubClient library.

**Comment by ChuckBell** [comment]
Have you tried changing the include file in the connector? That usually
solves the problem.

**Comment by topdancer** [comment]
Thanks, Chuck, this solved my issue.
