### ISSUE TITLE
Compatibility with W5500

### ISSUE THREAD

**Issue by wallisonferreira** [ChuckBell/MySQL_Connector_Arduino#59]
Hi, I'm having trouble trying to use the connector with a W5500-based shield, made by RoboCore in Brazil (https://www.robocore.net/loja/produtos/arduino-shield-ethernet-w5500.html).

They do have their own library, and I just thought if is there some way of making it compatible with the connector.

Here it is their library.
[Ethernet_W5500.zip](https://github.com/ChuckBell/MySQL_Connector_Arduino/files/2248732/Ethernet_W5500.zip)

I'm using their Mega-similar board (BlackBoard Mega -> https://www.robocore.net/loja/produtos/blackboard-mega.html), their ethernet shield (as mentioned above) and the Arduino IDE 1.8.5.

**Comment by ChuckBell** [comment]
It appears the library (Ethernet_W5500) may be compatible. Open the MySQL_Packet.h header file for the connector and replace the include to include the new library then try a simple sketch that only connects. If it compiles without errors and connects, that's a good enough smoke test. Note that you must have the W5500 library installed correctly for it to compile.

I tried it locally and it seems to compile just fine, but I don't have a board to test it.

**Comment by jordicasals** [comment]
Hello,

I suggest you to change the
```
#include <Ethernet.h>
```
by:
```
#include <Client.h>
```
Only the Client class is needed in the MySQL_Packet.

I think that it is also necessary to include the `Arduino.h` in MySQL_Packet.h

Thank you

**Comment by Bolukan** [comment]
See https://github.com/ChuckBell/MySQL_Connector_Arduino/pull/66

**Comment by ChuckBell** [comment]
Closed due to inactivity. Please open a new ticket if this is still relevant.
