### ISSUE TITLE
Issue in conn.conect(...) on Intel Galileo Gen 2

### ISSUE THREAD

**Issue by 0307081** [ChuckBell/MySQL_Connector_Arduino#6]
Hi, i'm trying to run the basic example of the library but the Sketch stops in the line "if (conn.connect(server_addr, 3306, user, password))" .
I don't know what could be the problem.
this is the code
`#include <Ethernet.h>`
`#include <MySQL_Connection.h>`
`#include <MySQL_Cursor.h>`

`IPAddress server_addr(192,168,1,100);  // IP of the MySQL *server* here`
`char user[] = "cymo";              // MySQL user login username`
`char password[] = "cymo";        // MySQL user login password`
`// Sample query`
`char query[] = "SELECT * FROM cymo_db.login";
`
`EthernetClient client;`
`MySQL_Connection conn((Client *)&client);`
`// Create an instance of the cursor passing in the connection`
`MySQL_Cursor cur = MySQL_Cursor(&conn);
`
`void setup() {`
 ` Serial.begin(115200);`
 `  // eglibc ethernet naming...`
`  system("ifconfig eth0 192.168.1.222 netmask 255.255.255.0");`
`  Serial.println(Ethernet.localIP());`

`  while (!Serial); // wait for serial port to connect`
  
`  Serial.println("Connecting...");`
`  if (conn.connect(server_addr, 3306, user, password)) {`
    `delay(1000);`
`  }`
 ` else`
  `  Serial.println("Connection failed.");`
`}`

When I upload the sketch to the galileo and turn on the serial monitor i can see
192.168.  1.222
Connecting...

and nothing else of the sketch keeps running.
I don't know if this is the right place to ask for this, but in your Blog i couldn't do it.
Thanks.

Roberto

**Comment by ChuckBell** [comment]
Hi. You can ask questions on the Oracle C/Ard forum: http://forums.mysql.com/list.php?175. I had to close posts on my blog due to a rash of spammers polluting the comments. Sorry about that. You can also contact me directly at d r c h a r l e s b e l l at g m a i l dot c o m.

Have you followed the troubleshooting tips explained in the manual? More specifically, you should ensure your Ethernet connectivity is working by testing with one of the Ethernet sample sketches. Once you can establish communications, you can then begin troubleshooting the issue. In my experience, it is most likely networking related - either the network you are using for the server is unreachable, you're using the wrong IP address (remember, you need the address of the MySQL server, not your board - a common mistake), or there is something wrong with the networking hardware.

**Comment by ChuckBell** [comment]
You should also try testing the "connect" sketch in the connector examples and omit any extra statements (like the system call, setting up the query, cursor, etc.) - strip it to the bare minimum. 

Finally, and I think this may be your problem, you are missing the call to initialize the Ethernet class (another reason to start with the sample sketches):

...
  Serial.begin(115200);
  while (!Serial); // wait for serial port to connect
  Ethernet.begin(mac_addr);   // <============= HERE
  Serial.println("Connecting...");
...

See the sample "connect" sketch for more details.

**Comment by 0307081** [comment]
Hi Dr. Bell, I've tried the example you said just as it comes but have the
same problem. when I use an other ip address for the server I can get to
the fail connection message but when I use the one it should crashes.
I can reach the server from an other pc and even from the console through
the lan ip instead of just use localhost or 127.0.0.1
thanks!
Roberto

**Comment by ChuckBell** [comment]
Please discontinue using this forum for this discussion. You may contact me via email as I have posted previously.

**Comment by ChuckBell** [comment]
You may also start a conversation on http://forums.mysql.com/list.php?175.

**Comment by ChuckBell** [comment]
The on-board Ethernet is not fully Arduino Ethernet compatible and therefore not usable with the connector. I will test with a normal Ethernet shield.

**Comment by ChuckBell** [comment]
The connector is not compatible with the onboard Intel Galileo Gen 2 Ethernet. Please consider using an Arduino board instead.

**Comment by ChuckBell** [comment]
That said, I can make the connector work with the Galileo. Send me email to the address I listed above and I'll show you how.

**Comment by ChuckBell** [comment]
27 November 2017 UPDATE:

There are several issues that may cause the Galileo 2 Ethernet to fail to connect.

- the MAC address in your sketch must match the Galileo
- You must add a call to the system to setup the Ethernet correctly
- The Ethernet Client.available() method doesn't return the correct number of bytes in the queue.

Fixing the first two is easy - just modify your sketch as follows (it's an excerpt).

byte mac_addr[] = { 0x98, 0x4F, 0xEE, 0x05, 0x30, 0xEB };
...

void setup() {
  Serial.begin(115200);
  while (!Serial); // wait for serial port to connect

  Serial.print("Configuring the Ethernet interface...");
  system("ifup eth0");  
  delay(2000);
  Serial.println("done.");
  Serial.print("Waiting for Ethernet interface to start...");
  delay(2000);    // Open serial communications and wait for port to open:
  if (Ethernet.begin(mac_addr) == 0) {
    Serial.println("ERROR: Failed to configure Ethernet using DHCP!");
  } else {
    Serial.println("done.");  
  }
  Serial.print("IP: ");
  Serial.println(Ethernet.localIP());
  delay(2000);
...

Fixing the last one requires modifying the connector code. Open the MySQL_Packet.cpp file and comment out the loop in the read_packet() method as follows.

void MySQL_Packet::read_packet() {
  byte local[4];

  if (buffer != NULL)
    free(buffer);

/*
  int avail_bytes = wait_for_client();
  while (avail_bytes < 4) {
    avail_bytes = wait_for_client();
  }
*/
  // Read packet header
...
