### ISSUE TITLE
Using mySQL with 2 db names 

### ISSUE THREAD

**Issue by a55830** [ChuckBell/MySQL_Connector_Arduino#61]
hi
amazing script , thx for this
but i have a little problem , i connect fine but....
i need to supply a name because there is more db's on that ip
in php i do this : $link = new mysqli('server', 'user', 'password', 'DatabaseName')
if i dont give the   DB name then i can connect to the database

is there anywhere i can put it, i tryed :   if (conn.connect(server_ip, 3306, mysqlusr, mysqlpws, db_name) 
but it dont work

**Comment by ChuckBell** [comment]
Hi,

Yes, that feature can be added. Let me work on that. Could be just the kick I need to release the next version.

Stay tuned…

Dr. Bell

**Comment by seaburngames** [comment]
any news on this ?

**Comment by fabienroots** [comment]
Hi, I have the same problem with multy db.
Have you fix it ? 
Or have find an other library ?
Thanks in advance !

**Comment by ChuckBell** [comment]
No, not yet. Can you not work around it by including the database in the query?

**Comment by ChuckBell** [comment]
I have a patch ready to test. Would you like to try it out? If so, please
PM me at d r c h a r l e s b e l l at g m a i l dot c o m. I'll send you a
.diff which you can apply to the latest code in github (may not apply to
the one from library manager).
