### ISSUE TITLE
Not working on ESP32

### ISSUE THREAD

**Issue by SHIINA96** [ChuckBell/MySQL_Connector_Arduino#64]
I'm trying to run your code on my ESP32 Dev Module, and I can't compile the code.
Here is what I get from the IDE

Arduino: 1.8.7 (Mac OS X), Board: "ESP32 Dev Module, Disabled, Default, QIO, 80MHz, 4MB (32Mb), 921600, None"

Wrote 612256 bytes (369701 compressed) at 0x00010000 in 6.2 seconds (effective 786.1 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 144...

Writing at 0x00008000... (100 %)
Wrote 3072 bytes (144 compressed) at 0x00008000 in 0.0 seconds (effective 1527.6 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
/Applications/Arduino.app/Contents/Java/libraries/Ethernet/src/utility/w5100.cpp: In static member function 'static uint16_t W5100Class::write(uint16_t, const uint8_t*, uint16_t)':
/Applications/Arduino.app/Contents/Java/libraries/Ethernet/src/utility/w5100.cpp:315:22: error: no matching function for call to 'SPIClass::transfer(uint8_t [8], int)'
   SPI.transfer(cmd, 4);
                      ^
In file included from /Applications/Arduino.app/Contents/Java/libraries/Ethernet/src/utility/w5100.h:18:0,
                 from /Applications/Arduino.app/Contents/Java/libraries/Ethernet/src/utility/w5100.cpp:13:
/Users/barney/Documents/Arduino/hardware/espressif/esp32/libraries/SPI/src/SPI.h:69:13: note: candidate: uint8_t SPIClass::transfer(uint8_t)
     uint8_t transfer(uint8_t data);
             ^
/Users/barney/Documents/Arduino/hardware/espressif/esp32/libraries/SPI/src/SPI.h:69:13: note:   candidate expects 1 argument, 2 provided
/Applications/Arduino.app/Contents/Java/libraries/Ethernet/src/utility/w5100.cpp:369:29: error: no matching function for call to 'SPIClass::transfer(uint8_t [8], int)'
    SPI.transfer(cmd, len + 3);
                             ^
In file included from /Applications/Arduino.app/Contents/Java/libraries/Ethernet/src/utility/w5100.h:18:0,
                 from /Applications/Arduino.app/Contents/Java/libraries/Ethernet/src/utility/w5100.cpp:13:
/Users/barney/Documents/Arduino/hardware/espressif/esp32/libraries/SPI/src/SPI.h:69:13: note: candidate: uint8_t SPIClass::transfer(uint8_t)
     uint8_t transfer(uint8_t data);
             ^
/Users/barney/Documents/Arduino/hardware/espressif/esp32/libraries/SPI/src/SPI.h:69:13: note:   candidate expects 1 argument, 2 provided
/Applications/Arduino.app/Contents/Java/libraries/Ethernet/src/utility/w5100.cpp:371:23: error: no matching function for call to 'SPIClass::transfer(uint8_t [8], int)'
    SPI.transfer(cmd, 3);
                       ^
In file included from /Applications/Arduino.app/Contents/Java/libraries/Ethernet/src/utility/w5100.h:18:0,
                 from /Applications/Arduino.app/Contents/Java/libraries/Ethernet/src/utility/w5100.cpp:13:
Multiple libraries were found for "WiFi.h"
 Used: /Users/barney/Documents/Arduino/hardware/espressif/esp32/libraries/WiFi
 Not used: /Users/barney/Documents/Arduino/libraries/WiFi
 Not used: /Applications/Arduino.app/Contents/Java/libraries/WiFi
/Users/barney/Documents/Arduino/hardware/espressif/esp32/libraries/SPI/src/SPI.h:69:13: note: candidate: uint8_t SPIClass::transfer(uint8_t)
     uint8_t transfer(uint8_t data);
             ^
/Users/barney/Documents/Arduino/hardware/espressif/esp32/libraries/SPI/src/SPI.h:69:13: note:   candidate expects 1 argument, 2 provided
/Applications/Arduino.app/Contents/Java/libraries/Ethernet/src/utility/w5100.cpp: In static member function 'static uint16_t W5100Class::read(uint16_t, uint8_t*, uint16_t)':
/Applications/Arduino.app/Contents/Java/libraries/Ethernet/src/utility/w5100.cpp:416:22: error: no matching function for call to 'SPIClass::transfer(uint8_t [4], int)'
   SPI.transfer(cmd, 4);
                      ^
In file included from /Applications/Arduino.app/Contents/Java/libraries/Ethernet/src/utility/w5100.h:18:0,
                 from /Applications/Arduino.app/Contents/Java/libraries/Ethernet/src/utility/w5100.cpp:13:
/Users/barney/Documents/Arduino/hardware/espressif/esp32/libraries/SPI/src/SPI.h:69:13: note: candidate: uint8_t SPIClass::transfer(uint8_t)
     uint8_t transfer(uint8_t data);
             ^
/Users/barney/Documents/Arduino/hardware/espressif/esp32/libraries/SPI/src/SPI.h:69:13: note:   candidate expects 1 argument, 2 provided
/Applications/Arduino.app/Contents/Java/libraries/Ethernet/src/utility/w5100.cpp:418:24: error: no matching function for call to 'SPIClass::transfer(uint8_t*&, uint16_t&)'
   SPI.transfer(buf, len);
                        ^
In file included from /Applications/Arduino.app/Contents/Java/libraries/Ethernet/src/utility/w5100.h:18:0,
                 from /Applications/Arduino.app/Contents/Java/libraries/Ethernet/src/utility/w5100.cpp:13:
/Users/barney/Documents/Arduino/hardware/espressif/esp32/libraries/SPI/src/SPI.h:69:13: note: candidate: uint8_t SPIClass::transfer(uint8_t)
     uint8_t transfer(uint8_t data);
             ^
/Users/barney/Documents/Arduino/hardware/espressif/esp32/libraries/SPI/src/SPI.h:69:13: note:   candidate expects 1 argument, 2 provided
/Applications/Arduino.app/Contents/Java/libraries/Ethernet/src/utility/w5100.cpp:460:22: error: no matching function for call to 'SPIClass::transfer(uint8_t [4], int)'
   SPI.transfer(cmd, 3);
                      ^
In file included from /Applications/Arduino.app/Contents/Java/libraries/Ethernet/src/utility/w5100.h:18:0,
                 from /Applications/Arduino.app/Contents/Java/libraries/Ethernet/src/utility/w5100.cpp:13:
/Users/barney/Documents/Arduino/hardware/espressif/esp32/libraries/SPI/src/SPI.h:69:13: note: candidate: uint8_t SPIClass::transfer(uint8_t)
     uint8_t transfer(uint8_t data);
             ^
/Users/barney/Documents/Arduino/hardware/espressif/esp32/libraries/SPI/src/SPI.h:69:13: note:   candidate expects 1 argument, 2 provided
/Applications/Arduino.app/Contents/Java/libraries/Ethernet/src/utility/w5100.cpp:462:24: error: no matching function for call to 'SPIClass::transfer(uint8_t*&, uint16_t&)'
   SPI.transfer(buf, len);
                        ^
In file included from /Applications/Arduino.app/Contents/Java/libraries/Ethernet/src/utility/w5100.h:18:0,
                 from /Applications/Arduino.app/Contents/Java/libraries/Ethernet/src/utility/w5100.cpp:13:
/Users/barney/Documents/Arduino/hardware/espressif/esp32/libraries/SPI/src/SPI.h:69:13: note: candidate: uint8_t SPIClass::transfer(uint8_t)
     uint8_t transfer(uint8_t data);
             ^
/Users/barney/Documents/Arduino/hardware/espressif/esp32/libraries/SPI/src/SPI.h:69:13: note:   candidate expects 1 argument, 2 provided
exit status 1
Error compiling for board ESP32 Dev Module.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

Any help appreciated.

**Comment by sand007man** [comment]
Try to swap the referrence of ethernet.h in Packet.h to WiFi.h.

**Comment by SHIINA96** [comment]
It works but causes by the silly enterprise wifi, I gonna try it later.

**Comment by sand007man** [comment]
OK do let me Know once it is Working, even i am working with esp 32 :)

**Comment by ChuckBell** [comment]
That isn’t a message from the connector. That appears to be from the ESP WiFi library. Be sure to check for conflicts and ensure you’ve modified the connector header file correctly.

**Comment by mumairanwar92** [comment]
> I found that the variable ' statue ' didn't work properly. After I changed the whole WiFi connection part, the problem was fixed.

Hello, I'm having the same problem and I'm unable to fix it, can you guide what modification did you make ? Thanks in advance
