### ISSUE TITLE
Incompatibility of connector for ESP32 vs ESP8266 code

### ISSUE THREAD

**Issue by topdancer** [ChuckBell/MySQL_Connector_Arduino#70]
Hi,

As mentioned in issue 47, compiling ESP32 code referring to the connector fails with two errors in the module mySQL_Encrypt_Sha1.cpp in lines 89 and 95.
Adding a „Return 0“ statement in both functions solves the compile issue on ESP32.

However, if running some other code containing mySQL code on ESP8266 / ESP8285 devices (using such modified mySQL library as above!) results that the devices can’t connect to mySQL db. Any connection attempt immediately results in connection result FAILED.
As soon as I then remove/comment out both „Return 0“ statements in the Sha1 component, the connection is successful (which in turn would result in compile errors for code on my ESP32 system).

Can you verify this behavior?

Certainly can I change the code in Sha1.cpp depending on the device to be compiled, but isn’t there a more elegant solution for this behaviour?

Thanks,
Kurt

**Comment by ChuckBell** [comment]
I cannot verify the behavior. The code works as-is for me - I may not have the “right” ESP board. Which one are you using?

Regardless, I suggest making a conditional compilation to add the return for ESP32 boards. Would that solve your problem? If so, I’ll work on adding that (or you can suggest a patch if you’d like).

**Comment by topdancer** [comment]
Thanks Chuck. I was using two of the Chinese development boards (ESP32 & ESP8266). With my boards I can reproduce the behaviors.
Anyway, I am following your suggestion and and add conditional compile directives, this works.

Thanks,
Kurt
