### ISSUE TITLE
Remove Serial Output

### ISSUE THREAD

**Issue by At-M** [ChuckBell/MySQL_Connector_Arduino#72]
I'm using a ESP8266 as a wifi shield (yeah i know, but sadly it doesn't have enough ports for my usage) with an arduino.

The ESP and Arduino communicate via Serial, but the following strings interrupt my communication:

Connected to server version 5.5.57-MariaDB
Disconnected.

Is there a way to disable these outputs? I don't need them.

**Comment by ChuckBell** [comment]
Yes. Go into the code and comment out those statements. For example,
comment out line#86 in mysql_connection.cpp.

**Comment by At-M** [comment]
I just checked the headerfiles, not the cpp ones ugh..
*facepalm*

Thanks for your help :)
