### ISSUE TITLE
Error: 29 = No database selected.

### ISSUE THREAD

**Issue by seaburngames** [ChuckBell/MySQL_Connector_Arduino#74]
Hi I'm connecting to the server but unable to select my database...  
Probably similar as issue #61

```
85.233.********
Connecting...
Connected to server version 5.5.60-log

Running SELECT and printing results

Error: 29 = No database selected
```

**Comment by seaburngames** [comment]
im using this `char query[] = "SELECT * FROM RunningPrintJobs;";`

**Comment by ChuckBell** [comment]
So, add the database. :)

Mydbnamegoeshere.RunningPrintJobs

**Comment by seaburngames** [comment]
right so i added this : 

`char query[] = "USE PH123048_printtracker; SELECT * FROM RunningPrintJobs";`

getting this 
```

Connecting...
Connected to server version 5.5.60-log

Running SELECT and printing results













Disconnected.
```

**Comment by ChuckBell** [comment]
No, don’t use the use clause. You must add the dB name as I’ve suggested.

SELECT * FROM PH123048_printtracker.RunningPrintJobs

You cannot combine queries.

**Comment by seaburngames** [comment]
im sorry brains not working today, that removed the db error now im getting a 

`Memory error`

**Comment by ChuckBell** [comment]
Are you following the example sketch to read the columns and rows?

If you can’t figure it out, you can send me your sketch and I’ll look at it
when I get some time to tinker.

**Comment by ChuckBell** [comment]
I tested your sketch. The only thing I changed was I used IP to connect since DNS doesn't work reliably on my mobile network. And I changed the query to SELECT from world.city ... limit 10. Worked fine. I am also using MySQL 8.0.13.

Try again using IP to connect. If that doesn't work, try a newer version of MySQL.

What board are you using?

**Comment by ChuckBell** [comment]
I have a patch ready to test. Would you like to try it out? If so, please PM me at d r c h a r l e s b e l l at g m a i l dot c o m. I'll send you a .diff which you can apply to the latest code in github (may not apply to the one from library manager).

**Comment by Bolukan** [comment]
Surely,

 

If you include ESP32 I can test that too. Otherwise I start with ESP8266

 

#if defined(ESP8266) || defined(ESP32)

#include <Arduino.h>

#include <Client.h>

#else

#include <Ethernet.h>

#endif

 

Gerard
