### ISSUE TITLE
Connecting to localhost xampp

### ISSUE THREAD

**Issue by sh-raza** [ChuckBell/MySQL_Connector_Arduino#75]
NodeMCU can connect to the network already got IP and when it gets into the connecting to SQL the process just stops. Can someone figure why? , I'm using xampp phpmyadmin as a database.

**Comment by ChuckBell** [comment]
I'll need a lot more information than that. :) Also, you should check the documentation for examples on how to connect and start small by testing with the basic connect example. Beyond that, I'll need to know which board, what version of MySQL, the connector, and your sketch to be able to help you. Sorry.
