### ISSUE TITLE
WiFi Shields Compatibility

### ISSUE THREAD

**Issue by nikolovinn** [ChuckBell/MySQL_Connector_Arduino#77]
Hello there,

I was researching over the internet about Arduino -> MySql connection. I found your library and read the documentation. I liked how you documented the library and I would love to use it. However, I have a question regarding the WiFI Shield. As the Arduino WiFi Shield is "retired" now, could you please recommend me some other shields, tested by you, that will work with your library, without modifying the connector. As far as I understand the shield should work with the Ethernet.h of WiFi.h interface. But could you suggest shields like this? 

Thank you in advance!

Best regards,
Ivan

**Comment by Bolukan** [comment]
I would suggest a esp8266 (wifi) or w5100/w5300/w5500 ethernet module. The esp8266 can also be used as standalone device.

**Comment by ChuckBell** [comment]
+1  Arduino clone WiFi boards that support Ethernet class work too. I have
a couple of those. The Arduino WiFi 101 board works too if you can find one
of those.

Avoid any board that has its own library - those are unlikely to work.

**Comment by nikolovinn** [comment]
Thanks for the fast answers! I will start the process in a month and will let you know what I got and how it works :)
