### ISSUE TITLE
Connector and receive data from serial port

### ISSUE THREAD

**Issue by medved80** [ChuckBell/MySQL_Connector_Arduino#8]
I have a problem. I have rs485 and i am reading data from serial pins or softwareserial pins. Reading data is ok until I add code from connect to database. Databese connect is OK, but arduino do not reading data from serial pins. Thank´s.

**Comment by ChuckBell** [comment]
On the surface, it sounds like you have a conflict with one or more pins. That is, more than one library/device is using the same pin(s). Another possibility is you're running into conflicts within the libraries themselves. Yet another possibility is you're using an Arduino that doesn't have enough memory to load and execute all of the code you're using. 

However, I do not have enough information to process this issue and thus I cannot help beyond a mere guess at this point. I've seen similar issues posted many times and usually they turn out to be a simple matter of trying to do too much with too small amount of memory. But again, I can't say for certain without more information.

Please send me your complete sketch as well as a complete description of the Arduino board you're using, the network shield/module, other modules, libraries, and versions for the IDE, connector, and any other libraries you are using.

If I do not hear back from you in a couple of weeks, I may close the issue.
