### ISSUE TITLE
Why would anyone create a connection routine that can not use a host name?

### ISSUE THREAD

**Issue by dachshund-digital** [ChuckBell/MySQL_Connector_Arduino#81]
Why would anyone create a connection routine that can not use a host name?  I just can't believe there is a good reason for not doing this?  Please add this feature.  Having to use a static IP address as the database server specification is so regressive.  Just not a best practice, at all.

**Comment by ChuckBell** [comment]
Why your comments are welcome, they’re a bit over the top here. The reason
is simply the base libraries don’t support it. We are talking a wee small
machine here. If your platform has libraries that support lookups, you can
implement that yourself. Most can’t spare the memory. Please keep this
forum constructive.

**Comment by ChuckBell** [comment]
If you can suggest code to effect such a feature reliably for the Arduino libraries, please feel free to submit a patch or, if you want to support a specific platform, fork the code. :)
