### ISSUE TITLE
connecting a esp8266 NodeMCU failed to failed 

### ISSUE THREAD

**Issue by jcd420** [ChuckBell/MySQL_Connector_Arduino#82]
what am I doing wrong?

#include <ESP8266WiFi.h>
#include <ESP8266WiFiMulti.h>
#include <MySQL_Connection.h>
ESP8266WiFiMulti WiFiMulti;
WiFiClient  client;

IPAddress server_addr(192, 168, 0, 103);  // IP of the MySQL *server* here
char user[] = "admin";              // MySQL user login username
char password[] = "my123";        // MySQL user login password

MySQL_Connection conn((Client *)&client);

void setup() {
   Serial.begin(9600); // Open serial connection to report values to host
   Serial.println("Starting up");
     delay(10);

  // We start by connecting to a WiFi network
  WiFi.mode(WIFI_STA);
  WiFiMulti.addAP("JC", "1234abcd");
  Serial.print("Wait for WiFi... ");
  while (WiFiMulti.run() != WL_CONNECTED) {
    Serial.print(".");
    delay(500);
  }
  Serial.println("");
  Serial.println("WiFi connected");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());

 
}

void loop() { 
  
  if (conn.connect(server_addr, 3306, user, password)) {
    delay(1000);
    Serial.println("Connection made :)");

  }
  else
    Serial.println("Connection failed.");
  conn.close();
}

**Comment by ChuckBell** [comment]
I need a wee bit more information. What isn’t working? Is there an error?
What board are you using and what are you using the multi library?

**Comment by jcd420** [comment]
The board is  ESP8266 NodeMCU Lua
the erro I get is: Connection failed.

I am new to programming and I copied the scrip from another site. I will remove the multi.

i can connect from other computers to the SQL server. I can not connect to server. I connect to DHCP server and get an IP. Is there any other mistakes I make on my script?

**Comment by jcd420** [comment]
I think that the  WiFiMulti is need to get internet connection.

**Comment by jcd420** [comment]
I did a script with out the Multi. but same error.




//#include <ESP8266WiFiMulti.h>
#include <MySQL_Connection.h>
#include <ESP8266WiFi.h>

const char* ssid     = "JC";
const char* password = "1234abcd";


IPAddress server_addr(192, 168, 0, 103);  // IP of the MySQL *server* here
char user[] = "admin";              // MySQL user login username
char passwordSQL[] = "my123";        // MySQL user login password
WiFiClient client;

MySQL_Connection conn((Client *)&client);

void setup() {
   Serial.begin(115200);
  delay(10);

  // We start by connecting to a WiFi network

  Serial.println();
  Serial.println();
  Serial.print("Connecting to ");
  Serial.println(ssid);
  WiFi.mode(WIFI_STA);
  WiFi.begin(ssid, password);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  Serial.println("");
  Serial.println("WiFi connected");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());

 
}

void loop() { 
  
  if (conn.connect(server_addr, 3306, user, passwordSQL)) {
    delay(1000);
    Serial.println("Connection made :)");

  }
  else
    Serial.println("Connection failed.");
  conn.close();
}

**Comment by Bolukan** [comment]
Don’t know whether it solves anything, but I use
MySQL_Connection conn(&client);
I don’t recast and I doubt Client is the same as client.

Further no strange code. Is your port the standard 3306?

**Comment by ChuckBell** [comment]
Ok, I understand. First, you don't need the multi library. Second, to use a
library other than the included Arduino libraries, you must modify one of
the connector files. You must replace #include <Ethernet.h> with
#include<ESP8266WiFi>. This is in MySQL_Packet.h. Beyond that, and removing
the multi code, your sketch should be Ok. Look at other posts on the forum
regarding ESP8266 for more hints and solutions. I don't use those boards
very often because they're far too small for some of my projects, but I
have tested (and used) the connector with several varieties of ESP boards
for small projects.

**Comment by Bolukan** [comment]
I already did it:
https://github.com/ChuckBell/MySQL_Connector_Arduino/compare/master...Bolukan:master
I think it is a good guess for all ESP8266 users (using WiFi in stead of Ethernet) this is a good solution. I will change my code change to a conditional one and do a pull request.

**Comment by ChuckBell** [comment]
Ok, and if everything is working correctly, we can close the issue.

**Comment by jcd420** [comment]
I did it all and still same erro :(
this is how the code look now

#include <ESP8266WiFi.h>              
#include <MySQL_Connection.h>
#include <MySQL_Packet.h>

IPAddress server_addr(192, 168, 0, 103);  // IP of the MySQL *server* here
char user[] = "admin";              // MySQL user login username
char password[] = "my123";        // MySQL user login password

WiFiClient client;
MySQL_Connection conn((Client *)&client);

void setup() {
  //----------------wifi ----------------------------------
  Serial.begin(115200);
  Serial.println();
  WiFi.begin("JC", "1234abcd");
  Serial.print("Connecting");
  while (WiFi.status() != WL_CONNECTED)
  {
    delay(500);
    Serial.print(".");
  }
  Serial.println();
  Serial.print("Connected, IP address: ");
  Serial.println(WiFi.localIP());
//---------------------wifi-----------------------------------

  Serial.println("Connecting...");
  if (conn.connect(server_addr, 3306, user, password)) {
    delay(1000);
  }
  else
    Serial.println("Connection failed.");
  conn.close();
}

**Comment by ChuckBell** [comment]
If you are getting a connection failed error, it is a good possibility either your board isn't connected to the right network (has no route to the server), or you can one or more of the common problems listed in the user's manual such as MySQL permissions issues, wrong IP address for the server, a firewall blocking port 3306, etc.

BTW, are you sure your server is listening on 192.168.0.103? Read the manual for more hints on how to diagnose connection issues.

What IP address is shown in the serial monitor for your board?
