### ISSUE TITLE
Input database IP address

### ISSUE THREAD

**Issue by SHIINA96** [ChuckBell/MySQL_Connector_Arduino#87]
Hello,
I'm trying to build my project with the connector, and the problem is the IP address of my MySQL database may changed often. Cause I need to work both at home and school. I'm trying to catch the IP address input from serial monitor. But it seems Arduino not allowed to define IP address as a string or char.
And attached link is my own project: https://github.com/SHIINA96/IoT_System_with_ESP32
Is there any help?

**Comment by ChuckBell** [comment]
That depends...are you willing to test out a new feature that allows you to
connect via hostname? Would that work for you? Let me know and send me your
private email address and I'll email you a patch.

Also, make sure you close the connection each time in your code. Not
closing connections and freeing cursors will cause your sketch to fail or
become unstable.

**Comment by SHIINA96** [comment]
Yes, please Dr.Bell. Here is my private email: b a k ei m o n o  at  g mail dot com.

About the connection. I notcied that everytime the upload process will have 2-3 seconds delay, I thought it will accelerate the process without the close commond.
