### ISSUE TITLE
How to passing Integer values to sprintf

### ISSUE THREAD

**Issue by 3rc0** [ChuckBell/MySQL_Connector_Arduino#89]
Example:

char UPDATE_DATA[] = " UPDATE dbName.dbName SET COL1 = %d, COL2 = %d WHERE COL3 = %d";
char query[128];

unsigned int num1 = 1;
unsigned int num2 = 1111;
unsigned int num3 = 5;

Is this one correct?
 sprintf(query,UPDATE_DATA, %d, %d, %d, num1, num2, num3);

 or there is another way to pass integers to the query update?!

**Comment by Bolukan** [comment]
No not correct, check the [syntax of sprintf](https://linux.die.net/man/3/sprintf):
`int sprintf(char *str, const char *format, ...);`

so try: (const is not necessary, but just to be clear)
```
const char* UPDATE_DATA = "UPDATE dbName.dbName SET COL1 = %u, COL2 = %u WHERE COL3 = %u";
char query[128];
sprintf(query,UPDATE_DATA, num1, num2, num3);
```

**Comment by ChuckBell** [comment]
Correct. Just watch your length for the buffer (query).

**Comment by 3rc0** [comment]
Thank you @Bolukan your method is working perfect ( I tested without  const ).
Thank you @ChuckBell for the quick response. The problem was I an issue with W5100 module, so I bought a new W5500 module and now everything works amazingly.

**Comment by ChuckBell** [comment]
Ok, can we close the issue?

**Comment by 3rc0** [comment]
Yes.

**Comment by 3rc0** [comment]
@ChuckBell Is there possible to track usage of "query" length and bytes get it with Serial.print()? because I have multi statements and afraid with working on it will get issue?!

**Comment by ChuckBell** [comment]
You can use strlen(query), which will tell you how many characters (bytes for single-byte charsets) are in the string. So, you can check in advance or detect when you're overflowing your buffer.

**Comment by JanissaryID** [comment]
Please Help me for solve my problem
char waktu[] = "09:00:00";
char UPDATE_SQL[] = "UPDATE employeedb.presence SET TimeIn = '%c' WHERE id = 1",waktu;
its not correct

**Comment by ChuckBell** [comment]
You're trying to format a string. You need to use %s and sprintf(). See the example sketches. This technique is shown there.
