### ISSUE TITLE
Using MySQL with an Arduino Uno Wifi

### ISSUE THREAD

**Issue by FelixB91** [ChuckBell/MySQL_Connector_Arduino#9]
I'm using the [Arduino Uno Wifi](http://www.arduino.org/products/boards/arduino-uno-wifi). I want to send the data I collect to a MySQL Database. When using the basic example 'basic_insert', the Arduino tries to make a connection via ethernet (Ethernet.h), which I don't have and don't need. I think the critical point is here
```c++
EthernetClient client;
MySQL_Connection conn((Client *)&client);
```
Is there no other way to establish a connection without using EthernetClient?

Thanks in advance!

**Comment by mserra1** [comment]
The Arduino Uno Wifi uses an ESP8266 chip, so you should be able to use any MySQL_Connector compatible wifi package in your sketch, such as ESP8266WiFi.  Haven't used the Uno Wifi myself so I am just guessing that there isn't some other complication involved.  The following worked for me on the LoLin NodeMcu V3 board:

```
#include <ESP8266WiFi.h>

WiFiClient client;
MySQL_Connection conn((Client *)&client);
```

**Comment by FelixB91** [comment]
Thanks for your replay @mserra1 !
I tried it and know it works until the point, where I can successfully compile it. When I upload the sketch to my Arduino it permanently tries to connect and resumes to do so without an error message, but also without any results.
I guess it´s because I removed the 'Ethernet.begin(mac_addr);' part from the setup() function, since I don´t know what it does and couldn't find a way to make it work with the ESP8266wifi.h library?
Any suggestions how I could fix that?

```c++
#include <ESP8266wifi.h>
#include <MySQL_Connection.h>
#include <MySQL_Cursor.h>

byte mac_addr[] = { 0xDE, 0xAD, 0xBE, 0xEF, 0xFE, 0xED };

IPAddress server_addr(88, 198, 61, 231);  // IP of the MySQL *server* here
char user[] = "USERxxxxx";              // MySQL user login username
char password[] = "xxxxxxx";        // MySQL user login password

// Sample query
char INSERT_SQL[] = "INSERT INTO `arduino_test`(`Humidity`, `Temperature`, `DateTime`) VALUES (60, 23, '2017-02-02 12:34:20')";

WifiConnection client;
MySQL_Connection conn((Client *)&client);

void setup() {
  Serial.begin(9600);
  while (!Serial); // wait for serial port to connect
  //Ethernet.begin(mac_addr);
  Serial.println("Connecting...");
  if (conn.connect(server_addr, 3306, user, password)) {
    delay(1000);
  }
  else
    Serial.println("Connection failed.");
}


void loop() {
  delay(2000);

  Serial.println("Recording data.");

  // Initiate the query class instance
  MySQL_Cursor *cur_mem = new MySQL_Cursor(&conn);
  // Execute the query
  cur_mem->execute(INSERT_SQL);
  // Note: since there are no results, we do not need to read any data
  // Deleting the cursor also frees up memory used
  delete cur_mem;
}
```

**Comment by ChuckBell** [comment]
Hi,

Yes, you still need the begin() call in setup(). It should work with the library iff it is compliant with the Arduino Ethernet class. The fact that it compiles suggests that it is compliant. Which ESP8266 module do you have?

Dr. Bell

**Comment by FelixB91** [comment]
Honestly I don't know which ESP8266 module I have exactly. The Arduino Uno WiFi webpage only states

> Processor: ESP8266
Architecture: Tensilica Xtensa LX106

but that´s about it. I tried to find a function in the ESP8266wifi.h source code which compares to the Ethernet.h function but couldn't find any that works. Both

`WifiConnection.begin(mac_addr);`
and
`ESP8266wifi.begin(mac_addr);`
returns an error.

**Comment by mserra1** [comment]
Your unit is the Arduino Uno Wifi which has an ESP8266 chip soldered onto it.  Never seen it before myself but that's what the images I pulled up show.  So that's why I assumed you will be able to use ESP8266 libraries.

I forgot the begin statement as Dr. Bell suggested.  In the begin statement you will use your ssid and wifi pass as arguments:

```
char ssid[] = "your_ssid"
char pass[] = "your_pass"

void setup() {
    Serial.begin(115200); //your baud rate may be different, usually it is either 115200 or 9600 depending on device
    while (!Serial); //wait for serial port to connect
    Wifi.begin(ssid, pass);
    while (WiFi.status() != WL_CONNECTED) {
        delay(500);
        Serial.print(".");
    }
    Serial.println("WiFi connected");

    while (conn.connect(server_addr, 3306, user, pass) != true) {
        delay(500);
        Serial.print(".");
    }
    Serial.println("Ready");
    Serial.print("IP Address: ");
    Serial.println(WiFi.localIP());
}



```

**Comment by FelixB91** [comment]
Thank you very much @mserra1 for your explanatory answer. 

I think I used a completely different library for the ESP8266 the whole time. I used [this](https://github.com/ekstrand/ESP8266wifi) library the whole time. I think the library your code sample refers to is [this library](https://github.com/esp8266/Arduino/tree/master/doc/esp8266wifi). Unfortunately, this one doesn't work for me. Even the basic examples are causing an error. Plus, my IDE marks the examples as "[Incompatible](http://i.imgur.com/GePwZM5.png)".

The library I'm using which is "ESP8266wifi.h" and not "ESP8266WiFi.h" doesn't seem to work the same way and is throwing an exception at `while (WiFi.status() != WL_CONNECTED)` since it doesn't know WL_CONNECTED.

Beside that, the good thing at the Arduino Uno WiFi is supposedly the web interface. It looks like [this](http://www.arduino.org/images/tutorials/Arduino%20UNO%20WiFi%20section.png) and enables the Arduino to connect to a wifi network without having to implement it in the code first. I tested the connection with an successful HTTP request first, to see if the wifi is working correctly. So I´m not quite sure if I really need to connect to a wifi ssid in the code first.

**Comment by mserra1** [comment]
So you have tried the ESP8266WiFi library?  I would recommend at least trying it, you should be able to find it in the library manager.  Connecting to the wifi directly in the code in my opinion is more convenient as it is very straightforward and doesn't require additional work or a screen to connect.

**Comment by FelixB91** [comment]
I did try the ESP8266WiFi library ([like this](http://i.imgur.com/t2ZkA3A.png)), but it´s causing an error.

> /Arduino/libraries/ESP8266WiFi/src/ESP8266WiFiType.h:26:19: fatal error: queue.h: No such file or directory
 #include <queue.h>
compilation terminated.
exit status 1

When I manually search an download for queue.h it's causing the next exception and so on. I really don't know how to make it work. When I download the whole git repo and past the library folder into my Arduino working space it´s causing the same error somehow.

**Comment by ChuckBell** [comment]
Try using the one in the library manager named “UnoWiFi Developer Edition Library”. AFAICT, that’s the one I think you need but I don’t have any Uno’s with the WiFi to test.

**Comment by FelixB91** [comment]
@ChuckBell I did try this as you suggested, but once again I'm not sure if I'm doing it right. The "UnoWiFi Developer Edition Library" only contains two src files 

> UnoWiFiDevEd.cpp
UnoWiFiDevEd.h

This is how my complete code looks right now:

```c++
#include <UnoWiFiDevEd.h>
#include <MySQL_Connection.h>
#include <MySQL_Cursor.h>

IPAddress server_addr(88, 198, 61, 231);  // IP of the MySQL *server* here
char user[] = "USERxxxxx";              // MySQL user login username
char password[] = "xxxxxxx";        // MySQL user login password

// Sample query
char INSERT_SQL[] = "INSERT INTO `arduino_test`(`Humidity`, `Temperature`, `DateTime`) VALUES (60, 23, '2017-02-02 12:34:20')";

WifiData client;
MySQL_Connection conn((Client *)&client);

void setup() {
  Serial.begin(9600);
  while (!Serial); // wait for serial port to connect
  Wifi.begin();
  Serial.println("WiFi connected");

  while (conn.connect(server_addr, 3306, user, password) != true) { //3306 is the default MySQL port
    delay(500);
    Serial.print(".");
  }

  Serial.println("Connected to MySQL server.");
}


void loop() {
  delay(2000);

  Serial.println("Recording data.");

  // Initiate the query class instance
  MySQL_Cursor *cur_mem = new MySQL_Cursor(&conn);
  // Execute the query
  cur_mem->execute(INSERT_SQL);
  // Note: since there are no results, we do not need to read any data
  // Deleting the cursor also frees up memory used
  delete cur_mem;
}
```
It's derived from the "WebServer" examples from the library. I think I don't need pass Wifi.begin() any additional arguments, like SSID or PW since the Arduino is already connected to the wifi.

But it's causing an error from the MySQL_Connector 

> In file included from /Users/Felix/Documents/Arduino/libraries/UnoWiFi_Developer_Edition_Library/src/UnoWiFiDevEd.h:14:0,
                 from /Users/Felix/Documents/Arduino/SQL Test/basic_insert/basic_insert.ino:2:
/Users/Felix/Documents/Arduino/libraries/UnoWiFi_Developer_Edition_Library/src/lib/SC16IS750.h:107:33: error: expected ',' or '...' before '\x0'
 #define     EOL                 '\0'
                                 ^
/Users/Felix/Documents/Arduino/libraries/MySQL_Connector_Arduino/src/MySQL_Packet.h:69:43: note: in expansion of macro 'EOL'
     void show_error(const char *msg, bool EOL = false);
                                           ^
exit status 1

**Comment by FelixB91** [comment]
Ok, unfortunately it doesn't work yet. What I think is strange and what I only realised by now is that this code

```c++
WifiData client;
MySQL_Connection conn((Client *)&client);

void setup() {
  Serial.begin(9600);
  while (!Serial); // wait for serial port to connect
  Wifi.begin();
  
  Serial.println("Connecting");
  
  if (conn.connect(server_addr, 3306, user, password)) {
    delay(1000);
    Serial.println("Connection successful");
  }
  else {
    Serial.println("Connection failed!");
  }    
}
``` 

results in the serial monitor to constantly printing "Connecting". I expected the code to print "Connection failed" when the if statement fails or "Connection successful" in the other case. So why does it never happen? And why does the setup() function apparently loop?

**Comment by mserra1** [comment]
There are loops within the setup code that are looping, not the entire setup section itself.  It keeps printing Connecting because it is not getting the connection to wifi and simply can't move beyond that.  I have looked at a few Arduino Uno Wifi example sketches online (there really are not that many as I guess it is a new product) and they don't seem to initialize the wifi in this way, not that it is not possible, I am just not sure about that.

**Comment by ChuckBell** [comment]
Another possibility is the board is rebooting. I’ve seen this when the board was faulty and when the sketch was too large. When you compile, does the message state you have at least 512 bytes remaining? If < about 500 bytes, the sketch may hang or even cause the board to reboot.

**Comment by FelixB91** [comment]
@ChuckBell yes indeed. It tells me that "global variables use 84% of the dynamic memory" and that a lack of RAM can cause stability problems. But how can I detect if the board is actually rebooting? I mean the serial printer keeps printing "Connecting" in a 1 second time interval, if the board is actually rebooting, shouldn't the output be interrupted?

**Comment by ChuckBell** [comment]
Hi,

It’s kinda difficult to detect reliably when the board is resetting (other than the obvious). The interruption is not easy to witness since anything that is in the buffer to be sent to the Serial Monitor is abandoned when the board resets. So you’re only going to see messages that have completed. The only way around that, I suppose, is writing a character at a time. Then you may see a partial output.

What I’ve done in the past is trim down the sketch by removing code and libraries until I get it to work. Start with string constants - messages that you print out - and work down until you get the bare minimum.

Of course, this has taught me to start small when writing new sketches adding things one at a time and testing each iteration. ;)

I recommend you start small and work your way up trimming all unnecessary libraries, strings, and code until it becomes unreliable. You may find, as I have in the past, that refactoring your code may get you just enough space for the sketch to run.

Of course, the best way to avoid these issues - whenever possible - is to use a bigger board (one with more memory). ;)

Chuck

**Comment by FelixB91** [comment]
So, after some time a little update.
Your tip @ChuckBell was generally pretty good, I need to pay more attention to that matter in the future. However, the problem that occurred to me had a different origin. After reading through many post in the Arduino.org forum I discovered that people already had problems with their Arduino Uno Wifi back in March/April 2016. Apparently the developer didn't managed until today to make the standard Arduino libraries compatible with the "new" hardware. When asking people from the dev team on Arduino.org the standard answer is pretty much the same it used to be a year ago - we're working on it. That's it.
Since they call the Arduino Uno Wifi a "Development Edition" they say it's normal - but they also refuse to tell you that before you buy it. 

Anyway, I managed to write my data into a MySQL database by publishing the sensor results to ThingSpeak (an open source IoT application, which is pretty much the only thing that works with the Ciao library on the Uno Wifi) and then write a PHP script which is called by a cronjob to fetch data from ThingSpeak to my database. So, pretty ugly, but at least it works until someday the Arduino Uno Wifi becomes practically usable or I'll invest money in a shield. I wanted to write my approach down in case someone else stumbles upon the same problems as I did. 

Thanks again for your time and your help, I'll close this issue now.

**Comment by sunder11** [comment]
If you are looking for a solution to connect to a Mysql database using Chuck Bell's mysql connector by domain name (www.example.com) instead of a hard coded ip address, using wifi instead of ethernet, here is a working code sample to do database updates (Chuck had a sample for connecting by hostname using ethernet but not wifi).

It also has wifi server code (<WiFiManager>to connect and enter your ssid and password without having to hard code it (just use your phones wifi connection to connect to the server). https://github.com/tzapu/WiFiManager. The credentials will be stored in EEPROM.

I know this is an old thread but I had to rewrite my sketch because it would not compile anymore with the Aurduino IDE. (I spent 2 days going back and forth between trying to install the right version of the Aurduino IDE that would compile the old sketch, and updating the code to work in the newest version of the IDE). Updating the code won!

Here is a sample of the problem code in case anyone else is having this problem. Can't remember where I got it originally or if I just stumbled onto it.

----------------------------------------------------------------------
////////     Old Bad code ////////

byte mac_addr[] = { 0xDE, 0xAD, 0xBE, 0xEF, 0xFE, 0xED };
const char* host = "mallardalarm.com";
......
if (conn.connect(host, 3306, user, password)) {

Compilation error: conversion from 'char [17]' to 'IPAddress' is ambiguous
----------------------------------------------------------------------------------

```
#include <FS.h> //this needs to be first, or it all crashes and burns...
#include <WiFiManager.h>
#include <ESP8266WiFiMulti.h>
#include <MySQL_Connection.h>
#include <MySQL_Cursor.h>


char INSERT_SQL[] = "UPDATE mytestdatabase.users SET name='John Doe', phone_number='2125551212' WHERE user_id = '100'";


/////// WIFI-Client-DECLARATIONS/////////////////

WiFiClient client;            // Use this for WiFi instead of EthernetClient
ESP8266WiFiMulti WiFiMulti;

/////////END-WIFI-Client-DECLARATIONS////////


////////BEGIN-MYSQL-CONNECT DECLARATIONS CODE
byte mac_addr[] = { 0xDE, 0xAD, 0xBE, 0xEF, 0xFE, 0xED };

char hostname[] = "www.example.com"; 
char user[] = "yourusername";              // MySQL user login username
char password[] = "yourpassword";        // MySQL user login password
IPAddress server_ip;

int num_fails;                  // variable for number of failure attempts

#define MAX_FAILED_CONNECTS 5   // maximum number of failed connects to MySQL

MySQL_Connection conn((Client *)&client);
MySQL_Cursor cursor(&conn);
////////END-MYSQL-CONNECT-DECLARATIONS//////



//////////////////////// RUN-ONCE-CODE ///////////////////

void setup() {
  
  Serial.begin(115200);
  Serial.println();
  
 //BEGIN WiFi Connecton Manager//////////////////////////////////////////////////////////////////////////////

  WiFiManager wifiManager;

  wifiManager.setConfigPortalTimeout(180); //If no wifi credentials are entered it will reset in 180 seconds usful
                                           //in power failure when SA8266 boots up before home router when power restored.
  
  wifiManager.setBreakAfterConfig(true); //exit after config instead of connecting

  //RESET WIFI SETTINGS - UNCOMMENT for testing
  //wifiManager.resetSettings();

  // First it tries to connect to last known good settings//
  // If it does not connect it starts an access point//
  //// "The NodeMcu SSID", with password "password" // Blank "" //No password is required to connect
  ////Use Your phone or other device to connect to this wifi access point to ender wifi credentials ssid snd passwoed
  if (!wifiManager.autoConnect("Connect_TO_Your WIFI", "")) {
    Serial.println("failed to connect, we should reset as see if it connects");
    delay(3000);
    ESP.reset();
    delay(5000);
  }
 
  //if you get here you have connected to your WiFi
  Serial.println("connected..To WiFI:)");
  Serial.println("local ip");
  Serial.println(WiFi.localIP());
  
//END WiFi CONNECTION MANAGER///////////////CONNECTED/////////////////////////////////////////////////////////////////////

///// GET IP address of your mysql database using the domain name

if (WiFi.hostByName(hostname, server_ip)) {
    Serial.print("IP address of www.example.com: ");
    Serial.println(server_ip);
  } else {
    Serial.println("Unable to get example.com's IP Address");
  }
/////////////////End Get IP address///////////////////////

/////CONNECT to MYSQL Database using the server ip//
Serial.println("Connecting to MYSQL Database");
Serial.print("Using the hostname ");
Serial.println(server_ip);

if (conn.connect(server_ip, 3306, user, password)) {
    delay(1000);
    Serial.println("Connected to MySQL Database");
  }  else {
    Serial.println("Connection failed to MYSQL Database.");
}
///END CONNECT to MYSQL


}

//////////////////////// END-RUN-ONCE-CODE ///////////////////






//////////////////////// BEGIN RUN-LOOP-CODE ///////////////////

void loop() {

if (conn.connected()){
    Serial.println("Connection Good to MYSQL database.");
    Serial.println("Beginning to Record data in MYSQL database.");
    cursor.execute(INSERT_SQL);
    Serial.println("Updated MySQL database and set user's name to John Doe");
    Serial.println("Updated MySQL database and set user's phone number to 212.555.1212");
   } else { 
        Serial.println("Cant Connect to MYSQL database.");
        Serial.println("Retrying connection to MYSQL database.");
        if (conn.connect(server_ip, 3306, user, password)) {
        delay(1000);
              Serial.println("Connected to MySQL Database");
              Serial.println("Beginning to Record data in MYSQL database.");
              cursor.execute(INSERT_SQL);
              Serial.println("UUpdated MySQL database and set user's name to John Doe");
              Serial.println("Updated MySQL database and set user's phone number to 212.555.1212");
              }  else {
              Serial.println("Connection failed again to MYSQL Database.");
              num_fails++;
              if (num_fails == MAX_FAILED_CONNECTS) {
              Serial.println("Ok, that's it. I'm outta here. Rebooting...");
              delay(2000);
              ESP.reset();
          }
       }
     }
   } 

```
