### ISSUE TITLE
Select one row from one column for comparison

### ISSUE THREAD

**Issue by 3rc0** [ChuckBell/MySQL_Connector_Arduino#91]
I tried many methods to do select statement and to get the result one time to compare if  value there or not all get an issue with output, any idea how to re-structure the function to can work without error, example:

(num1, num2) 
 | 1      |    44  |
 | 2      |    55  |
  - - - - - - - - 

char selectNum [] = "SELECT num2 FROM dbName.tableName WHERE num2 = %d";

int numRow;

sprintf(query, selectNum, numRow)

int getInput = 55;

strcmp(getInput,rowValues);

Thanks.

**Comment by ChuckBell** [comment]
I need to see the rest of your code. Remember, the row returned is an array
so you’ll need to get the first item. See the sample sketches in the
connector for how to get the row result.

**Comment by 3rc0** [comment]
Thank you for your reply. Rest of code is long and unfinished.  The purpose I want a user typing a digits number by Keypad.h and passing to MySQL for comparing it if was available in the Database or not, I tried with examples available but the output is incorrect or gets an error.

**Comment by MariaMaria97** [comment]
Hello,
I am working on my Project Graduation and it's about the RFID (radio frequency identification) the idea is to compare the value of the tag seen on my serial monitor to the value present on my database (MYSQL) if it is the same access is authorized, if there is no tag on my database similar to the one seen on the serial monitor so access is denied.. can you help me to write this code!
Thanks a lot

**Comment by ChuckBell** [comment]
Hello. I will help you with specific issues, but I won't write the code for you. Please Google for examples of how to use RFID with Arduino. Get that working before you attempt to add the connector code. If you have issues using the connector, you may open an issue or contact me directly. Please do not over post on existing issues unless you have a similar problem. ;)

**Comment by 3rc0** [comment]
@MariaMaria97  the question is are you going to use  UID of RFID tag for authorization or write data on RFID tag for comparing with MySQL?! in this example source code taking input from Keypad to compare based what wrote on RFID for comparing.

**Comment by MariaMaria97** [comment]
I'm going to use UID of RFID tag for authorization !!

**Comment by 3rc0** [comment]
@MariaMaria97 which model of RFID you are using?! the library? or you start from scratch?!

**Comment by MariaMaria97** [comment]
I use the RFID reader MFRC522, and the library "MFRC522.h"

**Comment by MariaMaria97** [comment]
this is the library that I use: " https://github.com/miguelbalboa/rfid "

**Comment by 3rc0** [comment]
Good, your deadline for the project must present to the college?!
Based on your shared source code at #479 you wanna any time touched the RFID Tag to do comparing with MySQL for authorized, That means you wanna do input of a new UID tag manually in MySQL database?!

**Comment by MariaMaria97** [comment]
the deadline is June 15 but I have to realize these days because I have other tasks to do (link my database Mysql to Django framework to achieve the graphical interface and ...) in reality I will use 2 RFID systems: one for administration where we enter new tags and delete tags (as needed) and the other system for users where we have a program that controls access (denied access or authorized) and where we control tags from the database: who and when they entered?

**Comment by MariaMaria97** [comment]
by the way I'm using the Nodemcu esp8266, I wrote this sketch for the first RFID system (administration), but I didn't finish because I 'm not a good programmer:
#include <ESP8266WiFi.h>           // Use this for WiFi instead of Ethernet.h
#include <MySQL_Connection.h>
#include <MySQL_Cursor.h>
#include <SPI.h>
#include <MFRC522.h>

#define RST_PIN         D2          // Configurable, see typical pin layout above
#define SS_PIN          D4         // Configurable, see typical pin layout above

IPAddress server_addr(192,168,43,144);  // IP of the MySQL *server* here
char user[] = "******";              // MySQL user login username
char password[] = "*****";        // MySQL user login password

// Sample query
char INSERT_SQL[] = "INSERT INTO rfiddata.tag (tag_id) VALUES ()";

// WiFi card example
char ssid[] = "******";         // your SSID
char pass[] = "*******";     // your SSID Password

WiFiClient client;                 // Use this for WiFi instead of EthernetClient
MySQL_Connection conn(&client);
MySQL_Cursor* cursor;

MFRC522 mfrc522(SS_PIN, RST_PIN);  // Create MFRC522 instance

void setup() {
	Serial.begin(115200);		// Initialize serial communications with the PC
	while (!Serial);		// Do nothing if no serial port is opened (added for Arduinos based on ATMEGA32U4)
  // Begin WiFi section
  Serial.printf("\nConnecting to %s", ssid);
  WiFi.begin(ssid, pass);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  // print out info about the connection:
  Serial.println("\nConnected to network");
  Serial.print("My IP address is: ");
  Serial.println(WiFi.localIP());

  Serial.print("Connecting to SQL...  ");
  if (conn.connect(server_addr, 3306, user, password))
    Serial.println("OK.");
  else
    Serial.println("FAILED.");
  
  // create MySQL cursor object
  cursor = new MySQL_Cursor(&conn);
  
  if (conn.connected())
    cursor->execute(INSERT_SQL);
    
	SPI.begin();			// Init SPI bus
	mfrc522.PCD_Init();		// Init MFRC522
	mfrc522.PCD_DumpVersionToSerial();	// Show details of PCD - MFRC522 Card Reader details
	Serial.println(F("Scan PICC to see UID, SAK, type, and data blocks..."));
}

void loop() {
	// Reset the loop if no new card present on the sensor/reader. This saves the entire process when idle.
	if ( ! mfrc522.PICC_IsNewCardPresent()) {
		return;
	}

	// Select one of the cards
	if ( ! mfrc522.PICC_ReadCardSerial()) {
		return;
	}

	// Dump debug info about the card; PICC_HaltA() is automatically called
	mfrc522.PICC_DumpToSerial(&(mfrc522.uid));
}
Thanks

**Comment by 3rc0** [comment]
@MariaMaria97  Please check this source code is working fine with you?! if was everything ok let me know to do next step will connecting MySQL and passing UID to the database. 

P.S.  Post the error with a screenshot of the error.

```

/// edition 0.01


#include <ESP8266WiFi.h> // Use this for WiFi instead of Ethernet.h
#include <MySQL_Connection.h>
#include <MySQL_Cursor.h>
#include <SPI.h>
#include <MFRC522.h>


///////////////////////////
//// RFID Part ///////////
//////////////////////////

#define RST_PIN D2 // Configurable, see typical pin layout above
#define SS_PIN D4 // Configurable, see typical pin layout above

MFRC522 mfrc522(SS_PIN, RST_PIN); // Create MFRC522 instance

//////////////////////////
/////  MySQL Connector  //
//////////////////////////


IPAddress server_addr(192, 168, 43, 144); // IP of the MySQL server here
char user[] = "*"; // MySQL user login username
char password[] = ""; // MySQL user login password

MySQL_Connection conn(&client);
MySQL_Cursor* cursor;


// Sample query
///'%s' is passsing the string
char Insert_UID[] = "INSERT INTO rfiddata.tag (tag_id) VALUES (%s)";

/////////////////////////////////////
///////// WiFi Part  ///////////////
////////////////////////////////////

// WiFi card example
char ssid[] = ""; // your SSID
char pass[] = "*"; // your SSID Password

WiFiClient wifiClient; // Use this for WiFi instead of EthernetClient

/////////////////////////////////////
////// Selection part //////////////
////////////////////////////////////

int selectOption;



void setup() {

  Serial.begin(115200);  // Initialize serial communications with the PC
  while (!Serial);  // Do nothing if no serial port is opened (added for Arduinos based on ATMEGA32U4)
  // Begin WiFi section
  Serial.printf("\nConnecting to %s", ssid);
  SPI.begin();      // Init SPI bus
  WiFi.begin(ssid, pass);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  // print out info about the connection:
  Serial.println("\nConnected to network");
  Serial.print("My IP address is: ");
  Serial.println(WiFi.localIP());

  Serial.print("Connecting to SQL... ");
  if (conn.connect(server_addr, 3306, user, password)) {
    Serial.println("Connnected to MySQL Server");
  } else {
    Serial.println("Failed to connecting MySQL Server.");
  }
  Serial.println(F(" Initializing MFRC522."));

  mfrc522.PCD_Init();
  mfrc522.PCD_DumpVersionToSerial();

  Serial.println(F(" Please make sure the Tag card touched with RFID Reader before selecting the operation:\n\r [1] Authorization.\n\r [2] Add a new Tag card."));
}

void loop() {

  selectOption = Serial.read();

  switch (selectOption) {

    /// Option [1] for checking authorization of Tag card.
    case '1':
      Serial.println(F(" Option [1] procedure read tag card and checking the authorization."));
      mfrc522.PCD_SoftPowerUp(); // Turn On the RFID Reader.
      mfrc522.PCD_Init();   // Init MFRC522
      mfrc522.PCD_DumpVersionToSerial();  // Show details of PCD - MFRC522 Card Reader details


      if ( ! mfrc522.PICC_IsNewCardPresent() && ! mfrc522.PICC_ReadCardSerial()) { // Checking for presenting the Tag card.

        Serial.println(F(" Please make sure the Tag card touched with RFID Reader.")):

          return;
        }
        mfrc522.PICC_DumpToSerial(&(mfrc522.uid));

        // Passing the UID to MySQL










        break;

      /// Option [2] for adding a  new Tag card.
      case '2':
        Serial.println(F(" Option [2] procedure adding a new Tag card:"));
        mfrc522.PCD_SoftPowerUp();

        if (! mfrc522.PICC_IsNewCardPresent() && ! mfrc522.PICC_ReadCardSerial()) { // Checking for preseting the Tag card.


        Serial.println(F(" Please make sure the Tag card touched with RFID Reader."));

        return;
      }
      mfrc522.PICC_DumpToSerial(&(mfrc522.uid));
      //passing the UID to MySQL



      break;
    default:

      Serial.println(F(" Please choose one of these options:\n\r [1] Authorization.\n\r [2] Add a new Tag card."));

      break;

  }



  mfrc522.PCD_SoftPowerDown(); // Turn Off the RFID Reader.
}

```

**Comment by MariaMaria97** [comment]
thanks a lot I'm testing it, the source code is working fine but when I pass the tag I can't see my UID on my serial monitor and even on my table!§

**Comment by 3rc0** [comment]
Screenshot of Serial Monitor from beginning until tested both options!!

**Comment by MariaMaria97** [comment]
![image](https://user-images.githubusercontent.com/51048574/58820040-c8174b00-8631-11e9-90c1-9ee65b34b28c.png)
I don't see anything on my serial monitor when I pass the tag!!

**Comment by 3rc0** [comment]
You not supposed to pass over the Tag card, as I wrote must be already on (touched)  the RFID reader then choose the option you want, I do not see the version of MySQL @ChuckBell  is that mean there is no connection between Arduino and MySQL??! because with me will show the version while connected.
@MariaMaria97  You do not see anything, of course, I mentioned in the next step will be about passing the UID to MySQL ( table) in the database first finished the initializing and connection first.

**Comment by MariaMaria97** [comment]
I tested the example "basic_insert_esp8266" and w I wrote this query "char Insert_UID[] = "INSERT INTO rfiddata.tag (tag_id) VALUES ('FF10BA03')"; " and i can see it on my table without seeingthe version of mysql... the tag card was even on the rfid reader but I didn't see any thing!!

**Comment by MariaMaria97** [comment]
i think that seeing the version of mysql is not important!

**Comment by MariaMaria97** [comment]
look I can see the tag ID when I use an other example: 
![image](https://user-images.githubusercontent.com/51048574/58823800-d7e75d00-863a-11e9-822a-1b349883c812.png)

**Comment by MariaMaria97** [comment]
look I can see the tag ID when I use an other example: 
![image](https://user-images.githubusercontent.com/51048574/58823800-d7e75d00-863a-11e9-822a-1b349883c812.png)

**Comment by 3rc0** [comment]
MySQL must show the version based the instruction and I hope you followed because I took that steps are written in manual. 
https://github.com/ChuckBell/MySQL_Connector_Arduino/blob/master/extras/MySQL_Connector_Arduino_Reference_Manual.pdf

**Comment by MariaMaria97** [comment]
when I wrote this query: char Insert_UID[] = "INSERT INTO rfiddata.tag (tag_id) VALUES ('FF10BA03')"; I can see what I sent on my table:
![image](https://user-images.githubusercontent.com/51048574/58824340-21847780-863c-11e9-8b40-3e01c5c0c2a9.png)

**Comment by 3rc0** [comment]
I understand and of course, it will be recorded what you write but my point here going to pass from UID directly to MySQL and this point there is space.

**Comment by MariaMaria97** [comment]
So what are we going to do? it does not display the id tag on the serial monitor !!

**Comment by 3rc0** [comment]
I wrote I did changes, did you copy /paste and try it again? see the numbers ( /// edition 0.02
 ) in begin of the source code, will increase each time I do update.

**Comment by MariaMaria97** [comment]
okey, just minute!!

**Comment by MariaMaria97** [comment]
Sorry, it didn't work :( the  first sketch I sent shows me details about the tag id, I just didn't know how to sent the UID to my database!!

**Comment by 3rc0** [comment]
Try again this time, updated.

Understand what you trying to do but first, let finished the issue and debugging steps to understand what need to do. In your sketch, the Insert Query will execute one time without passing anything because you wrote empty > rfiddata.tag (tag_id) VALUES ()";< and supposed to be rfiddata.tag (tag_id) VALUES (%s)"; , %s is means passing string and %d integer.

**Comment by MariaMaria97** [comment]
Yes I didn't write anything in values just to let you write what you want,, one minute I' going to try the 3rd edition!!

**Comment by MariaMaria97** [comment]
the same problem :(

**Comment by 3rc0** [comment]
Screenshot?!

**Comment by MariaMaria97** [comment]
this is what it shows me when I test the sketch I sent writing %s in values: connexion is okey... I see details qbout the tag I pass but there is nothing in my database!!
![image](https://user-images.githubusercontent.com/51048574/58828178-2994e500-8645-11e9-98a1-91cf392db2a9.png)

**Comment by MariaMaria97** [comment]
screenshot about the third edition: the same I sent about the first edition!!

**Comment by ChuckBell** [comment]
Is this resolved? Can we close the issue?

**Comment by MariaMaria97** [comment]
we didn't resolve the problem !

**Comment by ChuckBell** [comment]
NAICT, the last iteration of the code did not have the query to insert the data into the MySQL database. You need to add the call(s) to do that after where the placeholder (comment) states. Do that, and you should see the data inserted in the table.

mfrc522.PICC_DumpToSerial(&(mfrc522.uid));
//passing the UID to MySQL

In pseudo code, it would be these statements:

create cursor
build SQL string (hint: sprintf)
execute query
close cursor

Look in the connector example sketches and you'll see how to do those steps. The trick is getting the value read from the RFID into the query, which you can do easily since it is a string. Remember to use a format string with quotes and %s.

**Comment by MariaMaria97** [comment]
I'm trying Dr. @ChuckBell 
I will let you know abot the result!!

**Comment by ChuckBell** [comment]
Closed due to inactivity. Please open a new ticket if this is still relevant.
